SAP/cloud-sdk-js

.github/workflows/build.yml
package.json
packages/analytics/package.json
packages/core/package.json
packages/generator/package.json
packages/test-util/package.json
packages/util/package.json
test-packages/integration-tests/package.json
test-packages/type-tests/package.json

* ignores changes to the .npmrc, so that lerna allows to publish canary releases
* adds changes to the packages, so that a realease is actually triggered

chore: fix canary release

---

.github/workflows/build.yml
.github/workflows/release.yml
docs/release.md
package.json

This PR adds a release build job. Tagged versions will be drafted for a release. Once a release is finalized a stable release  build is triggered, publishing our packaged to npm.

Add release build

---

CHANGELOG.md

chore: Update changelog for v1.18.0

---

.github/ISSUE_TEMPLATE/feature_request.md

Create issue template: feature request

---

package-lock.json
packages/analytics/package.json
packages/core/package.json
packages/generator/package.json
packages/test-util/package.json
packages/util/package.json
test-packages/integration-tests/package.json

Last time when updating jest, I did not update these jest related dependencies.

chore: update other jest related dependencies

---

packages/core/test/scp-cf/__snapshots__/vcap-service-destination.spec.ts.snap

Due to a mistake from my side, I merged a PR before a test assertion was changed. I do this with this PR.

Fix Failing Test

---

generate-docs.js

chore: adjustment for github pages

---

generate-docs.js

There are still some other links that need to be fixed.

chore: fix docs generator

---

generate-docs.js

Without VDMs, the search bar can work without waiting for generating index.
Additional adjustment is again needed for GitHub Pages.

chore:enable search bar

---

README.md
docs/how-to-switch-to-os-cloud-sdk.md

chore: add how to migrate to os sdk

---

package-lock.json
package.json
packages/generator/package.json

Update versions of productive dependencies in the generator (except for typescript).

chore: Update versions in generator

---

package-lock.json
packages/util/package.json

Another PR to loosen and update productive versions. This time for the util package.

chore: Update and loosen versions of util package

---

README.md

chore: add documentation link to the readme file

---

packages/generator/src/service/readme.ts
packages/generator/test/aggregator-package/readme.spec.ts
packages/generator/test/service/readme.spec.ts
packages/generator/test/test-util/readme-util.ts

The readme files of VDM packages now have the os repo link as the a useful link.

chore: add os repo link to readme of VDMs

---

packages/core/README.md
packages/generator/README.md
packages/test-util/README.md
packages/util/README.md
packages/util/src/logger/cloud-sdk-logger.ts

Add `installation`, `usage` and `api doc` to the readme of every package so that the npmjs can show them.

chore: improve readme for npmjs

---

package-lock.json
packages/core/src/request-builder/request-builder-base.ts
packages/core/src/request-builder/request/odata-request-config.ts
packages/core/src/request-builder/request/odata-request.ts
test-packages/integration-tests/test/request-builder.spec.ts

As requested in this question: https://answers.sap.com/questions/13017854/sap-cloud-sdk-for-javascript-custom-query-paramete.html
This allows to set custom query parameters, much like the custom headers

feat: Add custom query parameters option

---

CHANGELOG.md
packages/core/src/payload-value-converter.ts
packages/core/test/payload-value-converter.spec.ts

I just stumbled upon this and was wondering what went wrong here...

fix: Serializing of Edm.Int64

---

docusaurus.config.js

Updates config to enable Last Updated and Author

Enable Last updated and Author for documentation articles

---

docs/devops/getting-started.md

Update Getting Started for Pipeline

---

docusaurus.config.js

Fix logo link in the footer

---

knowledge-base/odata-v2-reusable-code.md
test-packages/integration-tests/test/complex-types.spec.ts

Reusable code list

---

.github/PULL_REQUEST_TEMPLATE.md
packages/core/src/request-builder/header-builder/authorization-header.ts
test-packages/integration-tests/test/__snapshots__/complex-types.spec.ts.snap

There was an `s` missing in the doc so the link did not work. If you have additional things feel free to highjack this PR.

Fix Link in Docs

---

knowledge-base/v4-api.md

This is the outcome of our api discussions. Please add anything if it is missing.

chore: v4 api proposals and decisions

---

scripts/generate-docs.js

Move the `version.js` to `api` folder to match the specification of the react component.

Patch version file to support Docusaurus

---

packages/analytics/package-lock.json
packages/analytics/package.json
packages/core/package-lock.json
packages/core/package.json
packages/generator/package-lock.json
packages/generator/package.json
packages/test-util/package-lock.json
packages/test-util/package.json
packages/util/package-lock.json
packages/util/package.json
test-packages/integration-tests/package-lock.json
test-packages/integration-tests/package.json

ts-jest 25.3.1 has some issues that you have to clean the cache all the time:
https://github.com/kulshekhar/ts-jest/issues/1506

use 25.4.0 of ts-jest

---

package-lock.json
package.json
scripts/generate-docs.js

Update typedoc to fix security advisory. I tested this locally, seems to work well.

chore: Update typedoc

---

docs/java/features/odata/generate-client.md

Changing `XML` -> `xml` to fix syntax highlighting. Tested it & for me it fixes the problems with the other pages as well 👍

Fix xml syntax highlighting

---

packages/generator/package-lock.json
packages/generator/package.json

chore: Add fs-extra types

---

docs/java/features/connectivity/destinations.md

Regex to find these things in the future: ` ```[A-Z]`
Should I create a GH action for it?

Fix syntax highlighting

---

docs/java/api-reference.md
docs/java/faq.md
sidebars.js

Please, review my initial FAQ section. Other changes are related to maintaining API docs for Java and adding FAQ to the sidebar.

Add FAQ. Update API reference for 3.19.1, Update sidebar

---

docs/java/features/multi-tenancy/thread-context.md
docs/java/features/odata/generate-client.md
sidebars.js

Explains the basic concept of the thread context and how to use it.
_Open for feedback_

Create initial documentation on the ThreadContext

---

docs/java/features/multi-tenancy/thread-context.md

`Jason Web Token` -> `JSON Web Token`

Fix typo in Thread Context docu

---

.eslintrc.js
packages/core/src/odata/v2/odata-batch-request-builder.ts
packages/core/src/odata/v4/odata-batch-request-builder.ts
packages/generator/src/generator-utils.ts
packages/generator/src/name-formatting-strategies.ts

I realized that this rule does not cover else if.

chore: Fix no-else-return rule

---

.github/PULL_REQUEST_TEMPLATE.md

chore: Remove label section from PR template

---

docs/js/introduction.md
docusaurus.config.js

@artemkovalyov : would that fix the "Edit this page" URLs for all pages (without custom edit URL)?

Point to edit URL

---

docs/java/features/odata/generate-client.md
docs/java/features/odata/use-vdm.md
docs/overview/key-features.md

I missed a few occurrences in #156 ...

Remove further occurrences of term VDM

---

.eslintrc.js
package-lock.json
package.json
src/pages/index.js
src/sap/utils/index.js

Things are growing little by little and we have to observe a good standard. Next steps:
- Adding pre-commit GitHub action
- Adding a linting to Pipeline

Adding Eslint, minor fixes to JS files

---

docs/java/features/odata/generate-client.md
docs/java/features/odata/overview.md
docs/java/features/odata/use-vdm.md
sidebars.js

- More semantic link slugs for Google to like it.
- Removed VDM from there
- Somewhat updated wording
Next step:
- Break this material down into the base and advanced cases.
- Extract logically independent items

Update links, fix wording in headers and sidebar

---

docs/java/features/rest/clients/scp-workflow-rest-api.md
docs/java/features/rest/overview.md
sidebars.js

My vision on our REST offering overview. I was confused for that Youtuber seeing an empty page)
Happy to hear your feedback and incorporate suggestions.

Overview section for REST and a bit of restructuring on sidebar

---

CHANGELOG.md
packages/generator/src/aggregator-package/package-json.ts
packages/generator/test/aggregator-package/package-json.spec.ts

Sets the correct version in the aggregator package.

fix: Generate aggregator packages with correct core dependency

---

packages/generator/src/aggregator-package/package-json.ts
packages/generator/test/aggregator-package/package-json.spec.ts

This script is not used anymore

chore: Remove unused after update script

---

packages/core/src/odata/v4/request-builder/get-by-key-request-builder.ts
packages/core/test/request-builder/get-by-key-request-builder-v4.spec.ts
packages/core/test/test-util/test-data.ts

feat: V4 get by key

---

packages/core/src/odata/common/edm-types.ts
packages/core/src/odata/common/uri-conversion/uri-value-converter.ts
packages/core/src/odata/v2/uri-conversion/uri-value-converter.ts
packages/core/src/odata/v4/request-builder/create-request-builder.ts
packages/core/src/odata/v4/uri-conversion/uri-value-converter.ts
packages/core/test/request-builder/create-request-builder-v4.spec.ts
packages/core/test/request-builder/create-request-builder.spec.ts
packages/core/test/test-util/request-mocker.ts
packages/core/test/test-util/test-data.ts
packages/core/test/test-util/testPostRequestOutcome.ts
packages/core/test/uri-value-converter-v4.spec.ts
test-packages/integration-tests/test/request-builder-v4.spec.ts
test-packages/integration-tests/test/test-data/single-test-entity-response-v4.ts

feat: V4 create

---

CHANGELOG.md

chore: Fix typo in changelog

---

packages/core/test/request-builder/update-request-builder-v4.spec.ts
packages/core/test/request-builder/update-request-builder.spec.ts
packages/core/test/test-util/request-mocker.ts
test-packages/integration-tests/test/request-builder-v4.spec.ts

Basically, just like the get/create request builder. Added some tests (with test entity) which are translated from the postman manual tests (against the reference services).

feat: V4 update

---

docs/java/features/multi-tenancy/thread-context.md
docs/java/getting-started.md
docs/java/tips-and-tricks/common-problems.md
sidebars.js
src/sap/roadmap/roadmap-java.js

This PR adds an article listing some common symptoms and how to address them. We can then link this in our issue template and point people towards it in order to reduce repetitive questions.

Java: Add documentation on common problems and how to approach them

---

docs/java/features/rest/clients/scp-workflow-rest-api.md

Added:
- Video tutorial
Fixed:
- Grammar

Add video tutorial for WF API used in Cloud SDK

---

docs/devops/getting-started.md

Brush up Continuous delivery section, add video

Next steps for continuous delivery "Getting starting" section + video

---

docs/js/guides/migrate-to-os.md

A mirror for migrating to OS on our docs

Migrate to OS

---

docs/devops/getting-started.md
docs/java/features/rest/clients/scp-workflow-rest-api.md
docs/java/video/connectivity-service.md
docs/java/video/getting-started-video.md
docs/java/video/odata-generator.md
sidebars.js
src/css/custom.css

New:
- Video Tutorials by Max in Java section
Fixes:
- Make youtube videos responsive.
- Update styles and HTML for relevant sections to make videos properly scale.

Add video tutorials for Java and fix styles for videos

---

packages/core/src/odata/v4/uri-conversion/get-expand.ts
packages/core/test/request-builder/get-all-request-builder-v4.spec.ts
packages/core/test/request-builder/request/get-expand.spec.ts
test-packages/integration-tests/test/request-builder-v4.spec.ts

feat: V4 expand subquery

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

So people don't get confused on where to open issues.

chore: Add note to issue template

---

packages/core/src/odata/common/filter/boolean-filter-function.ts
packages/core/src/odata/common/filter/filter-function-base.ts
packages/core/src/odata/common/filter/filter-function.ts
packages/core/src/odata/common/filter/filter-functions.ts
packages/core/src/odata/common/filter/filter.ts
packages/core/src/odata/common/filter/index.ts
packages/core/src/odata/common/filter/number-filter-function.ts
packages/core/src/odata/common/filter/string-filter-function.ts
packages/core/src/odata/v2/filter-functions.ts
packages/core/src/odata/v2/index.ts
packages/core/src/odata/v4/filter-functions.ts
packages/core/src/odata/v4/index.ts
packages/core/test/request-builder/request/v2/get-filters.spec.ts
packages/core/test/test-util/filter-factory.ts
test-packages/integration-tests/test/v2/filter-functions.spec.ts
test-packages/integration-tests/test/v4/filter-functions.spec.ts
test-packages/type-tests/test/filter.spec.ts
test-resources/service-specs/v2/API_TEST_SRV/service-mapping.json

Implemented all filter functions that are currently possible

feat: Add more filter functions

---

docs/java/features/connectivity/destinations.md

Adding section for decorating destinations.

Added section for Decorating Destination

---

docs/java/features/rest/clients/scp-workflow-rest-api.md

Updating an outdated method name

Update WF API method name

---

packages/core/src/odata/common/filter/boolean-filter-function.ts
packages/core/src/odata/common/filter/filter-function-base.ts
packages/core/src/odata/common/filter/filter-function.ts
packages/core/src/odata/common/filter/index.ts
packages/core/src/odata/common/filter/number-filter-function.ts
packages/core/src/odata/common/filter/orderable-filter-function.ts
packages/core/src/odata/common/filter/string-filter-function.ts
packages/core/src/odata/v2/filter-functions.ts
packages/core/src/odata/v2/index.ts
packages/core/src/odata/v4/date-filter-function.ts
packages/core/src/odata/v4/filter-function.ts
packages/core/src/odata/v4/filter-functions.ts
packages/core/src/odata/v4/index.ts
test-packages/type-tests/test/v4/filter-functions.spec.ts

Add some more filter functions that are based on DateTimeOffset.

feat: Add filter functions for dates

---

docs/java/troubleshooting.md

Java Docs: 
Add 403: Forbidden as symptom to existing note on on-premise connectivity.

Update Java troubleshooting docs

---

.github/workflows/build.yml

chore: Disable node 11 in the matrix of the workflow

---

packages/core/src/odata/v4/filter/filter-lambda-expression.ts
packages/core/src/odata/v4/request-builder/get-all-request-builder.ts

fix: Fix lambda usage on top level

---

CHANGELOG.md
packages/generator/src/generator-utils.ts
packages/generator/src/parser/common/edmx-to-vdm.ts
packages/generator/src/parser/v4/edmx-to-vdm.ts
packages/generator/test/generator-utils.spec.ts
test-resources/service-specs/v4/API_TEST_SRV/API_TEST_SRV.edmx

This fixes and skips some of the issues when generating v4 services. Also I added the changelog that I forgot on the previous PRs.

fix: Fix v4 generation

---

docs/java/features/bapi-and-rfc/overview.md

Refine local deployment section of BAPI documentation

---

docs/java/features/bapi-and-rfc/overview.md

This reverts commit 0809ab804918fa7d2853502d11072380ff0d3924.

Revert "Add section about destinations env var (#253)"

---

docs/java/guides/dependencies.md
docs/java/troubleshooting.md
sidebars.js

This PR introduces a guide on dependency management. It's rather minimal for now but provides some basic info on the SDK BOM and how to update SDK dependencies. 
I tried to only write SDK specific stuff and provide links to other sources for more general information. Of course the topic is huge so this is to be extended in the future.

Guide dependency problems

---

CHANGELOG.md
packages/core/package-lock.json
packages/core/src/odata/common/filter/boolean-filter-function.ts
packages/core/src/odata/common/filter/collection-filter-function.ts
packages/core/src/odata/common/filter/filter-function-base.ts
packages/core/src/odata/common/filter/filter-function.ts
packages/core/src/odata/common/filter/filter-functions.ts
packages/core/src/odata/common/filter/filter.ts
packages/core/src/odata/common/filter/filterable.ts
packages/core/src/odata/common/uri-conversion/get-filter.ts
packages/core/src/odata/v2/filter-functions.ts
packages/core/src/odata/v4/filter-function.ts
packages/core/src/odata/v4/filter-functions.ts
packages/core/test/request-builder/request/v2/get-filters.spec.ts
packages/core/test/request-builder/request/v4/get-filters.spec.ts
test-packages/type-tests/test/v4/filter-functions.spec.ts

Provide support for collection type filter functions.

feat: Support filter functions for collections

---

docs/java/features/bapi-and-rfc/overview.md

Refine plugin configuration for BAPI local deployment

---

packages/core/src/odata/common/entity-serializer.ts

chore: minor code improvement

---

package-lock.json
packages/generator/package-lock.json
test-packages/integration-tests/package-lock.json
test-packages/integration-tests/package.json

chore: Fix lodash dependencies

---

docs/java/troubleshooting.md

- Give hints on performance and provide a link on SCP docs about quotas and limitations.

A hint on performance for troubleshooting

---

package.json
packages/analytics/package.json
packages/core/package.json
packages/generator/package.json
packages/test-util/package.json
packages/util/package.json
test-packages/e2e-tests/package.json
test-packages/integration-tests/package.json
yarn.lock

This removes all the duplicate dev dependencies from our package.jsons. For simplicity.

chore: Remove unnecessary dev dependencies

---

packages/core/README.md
packages/generator/README.md
packages/test-util/README.md
packages/util/README.md

Update section on Documentation and Helpful links.

Update Readme in core

---

.github/workflows/build.yml
.github/workflows/release.yml

chore: Replace .npmrc with .yamlrc

---

.github/workflows/build.yml
.github/workflows/release.yml
.yarnrc
.yarnrc.yml
package.json
yarn.lock

This should fix our canary build

chore: Rename .yarnrc to .yarnrc.yml

---

packages/analytics/package.json
packages/core/package.json
packages/generator/package.json
packages/test-util/package.json
packages/util/package.json
test-packages/integration-tests/package.json

With the move to yarn workspaces the we broke the debug test scripts. This PR fixes them.

chore: Fix debug scripts

---

README.md

Fix main readme issues to the best of my knowledge

---

package.json

Update the home page for NPM module

---

README.md

Move docs to the beginning of the Readme

---

test-packages/test-services-e2e/package.json

There are 2 "scripts" key in the package.json, resulting the conflicts.

Fix: check dependencies

---

packages/generator/src/aggregator-package/package-json.ts
packages/generator/src/service/package-json.ts
packages/generator/test/aggregator-package/package-json.spec.ts

chore: Update generated homepage

---

docs/java/release-notes.md

3.26.0 release notes

---

CHANGELOG.md
packages/core/src/odata/common/uri-conversion/uri-value-converter.ts
packages/core/test/odata/uri-value-converter.spec.ts
packages/core/test/request-builder/get-all-request-builder.spec.ts

fix: Url encoding

---

docs/java/features/bapi-and-rfc/overview.md

minor clarifications in JCo doc

---

docs/java/getting-started.md

Spelling correction - Updated getting-started.md

---

README.md

Our docs writing guidelines from feedback collected in the previous PR https://github.com/SAP/cloud-sdk/pull/242

How we write

---

docs/java/features/odata/overview.md

Demonstrate the value of a type-safe OData client for different use-cases

Add use-cases for OData client

---

docs/java/features/connectivity/destinations.md

Improve destination docu

---

package-lock.json
package.json

When running `npm install` in the documentation branch, I got 71 audit issues. This leaves us with 6.

Update documentation dependencies

---

docs/js/features/odata/redirect-use-typed-odata-client-for-js.md

Not sure why this one redirect does not work, because it works locally. This is to try, whether the notation is different here.

docs: Try to fix redirect specific broken link

---

test-packages/test-services/v4/test-service/TestEntityLvl3MultiLink.js
test-packages/test-services/v4/test-service/TestEntityLvl3MultiLinkRequestBuilder.js

this will fix the broken master

chore: update test services

---

packages/generator/src/generator-cli.ts

fix: generator cli description

---

.github/PULL_REQUEST_TEMPLATE_DOCS.md

Having a meaningful pull request for Docs

Pull request template for docs

---

docs/js/features/odata/odata-v4-client.mdx

fix: a link in the filter doc

---

docs/js/features/odata/odata-v2-client.mdx

Added a section about how to use multiple changesets in a Batch.

doc: multiple changesets

---

docs/js/features/odata/odata-v4-client.mdx

Use pathname instead of absolute link

Remove absolute link

---

docs/java/features/connectivity/destinations.mdx

Fix typo in docs

---

docs/java/features/odata/generate-client.mdx

Add note about supported data types

---

docs/java/features/odata/type-safe-client-odata-v2.mdx

Adapts docu on deprecation. Relies on #469 to be merged first.

[Java] Update Docu on ETag Handling

---

CHANGELOG.md
packages/util/src/logger/cloud-sdk-logger.ts
packages/util/test/logger/cloud-sdk-logger.spec.ts

I am quite annoyed by the many log outputs we get in the tests. This is the first step towards making them disappear.

feat: Allow to mute loggers

---

docs/js/features/odata/odata-v2-client.mdx

[Doc]: function imports

---

package.json

chore: Expose all workspaces

---

packages/core/src/odata/common/response-data-accessor.ts
packages/core/src/odata/v2/request-builder/response-data-accessor.ts
packages/core/src/odata/v4/request-builder/response-data-accessor.ts

This will make it easier to consume the reponse data accessor.

chore: Add response data accessor interface

---

packages/core/src/odata/v2/entity-deserializer.ts
packages/core/src/odata/v2/entity-serializer.ts
packages/core/src/odata/v4/entity-deserializer.ts
packages/core/src/odata/v4/entity-serializer.ts

Expose the entity de-/serializer modules to be used in a type safe manner.

chore: Expose entity de-/serializer

---

packages/core/src/http-agent.ts
packages/core/src/odata/v2/odata-batch-request-builder.ts
packages/core/src/odata/v4/odata-batch-request-builder.ts
packages/core/src/scp-cf/environment-accessor.ts
packages/generator/src/edmx-parser/legacy/common/edmx-to-vdm.ts
packages/generator/src/edmx-to-vdm/common/entity.ts
packages/generator/src/edmx-to-vdm/edmx-to-vdm-util.ts
packages/generator/src/name-formatting-strategies.ts
packages/util/src/array.ts
packages/util/test/array.spec.ts

We are slowly getting rid of rambda. `last` can be quite useful, so I added it to our util package.

chore: Add last function to util

---

docs/java/features/odata/type-safe-client-odata-v2.mdx
docs/java/features/odata/type-safe-client-odata-v4.mdx

Add docu about batch

---

CHANGELOG.md
packages/generator/src/generator-options.ts
packages/generator/src/generator.ts
packages/util/src/array.ts
packages/util/test/array.spec.ts

I had problems with running the generate with transpile locally. The system got overloaded by around 200 processes in parallel. I made an adjustment to do this in chunks of 16 services and await for these to get finished.
I think this could be wrong in the E2E tests since we did not await the result properly.

[Fix] Transpile services in chunks and await result

---

sidebars.js

Logging is listed twice for Java/Guides

Remove duplicate entry in sidebar

---

test-packages/e2e-tests/package.json
yarn.lock

I currently get these errors in the pipe:
```
error https://npm.sap.com/@sap/cds-reflect/-/cds-reflect-2.12.2.tgz: Integrity check failed for "@sap/cds-reflect" (computed integrity doesn't match our records, got "sha512-++By/q8KJMjskh4p9YXWYk+nFw1DgV/kjiliMLGBC/tvg0vAmHHVwHJX6h39XLABskibsNkVSqU6g5F8V26Ptw== sha1-Drsk7PwiLvNiRqJqUboOZHv1Bsk=")
```
The cds reflect comes in via the cds version. I try to update the vesrion. If does not help I have to adjust the yarn.lock file to mathch the hashes.

[Chore] Update CDS

---

docs/java/guides/logging-overview.mdx

This PR enhances the logging guide to also cover MTA build files.

Add example MTA file to logging guide

---

docs/java/features/bapi-and-rfc/overview.mdx
docs/java/release-notes.mdx
docs/js/faq.mdx
docs/js/getting-started.mdx
docs/js/release-notes.mdx

This PR introduces inclusive language as [announced here](https://blogs.wdf.sap.corp/sapnews_en/2020/09/replacing-insensitive-terms-to-make-the-software-industry-more-inclusive/).

Removed insensitive terms from docs

---

docs/java/release-notes.mdx

Release notes for 3.30.0. Please, check correctness, I updated them from our internal notes.
Is blockchain API already externally released?

Release notes Java SDK 3.30.0

---

CHANGELOG.md
packages/core/src/odata/common/request-builder/batch/batch-request-serializer.ts
packages/core/test/batch/__snapshots__/batch-request-serializer.spec.ts.snap
packages/core/test/batch/batch-request-serializer.spec.ts

Encode the urls in batch requests. Fixes #568.

fix: Add url encoding in batch

---

test-packages/e2e-tests/.npmrc

The npmrc should not be necessary.

chore: Remove npmrc

---

docs/js/features/odata/odata-v4-client.mdx
package-lock.json

Realized in a call today one import is missing.

[chore] add missing import

---

knowledge-base/architectural-decisions-records/sdk-2.0.md

chore: Add discussion on SDK 2.0

---

docs/js/faq.mdx
docs/js/features/connectivity/generic-http-client.mdx
docs/js/getting-started.mdx

docs: Reference new main links

---

docs/java/features/bapi-and-rfc/overview.mdx

This PR enhances the BAPI documentation about deploying to localhost with the Spring archetype.

Add Spring docu on local deployment

---

docs/java/getting-started.mdx

[java] Fix link to archetypes overview

---

packages/rest-generator/src/generator.ts
packages/rest-generator/test/rest-generator.spec.ts

fix: generator open api files synchronously  

---

docs/java/features/bapi-and-rfc/overview.mdx

Fix typo in BAPI documentation

---

docs/java/features/enterprise-messaging/overview.mdx
sidebars.js

Hiding article about messaging as the CAP docu about it is not yet public.

Hide sidebar entry and fix link

---

knowledge-base/adr/template-generation.md

ADR for template generation #687

chore: Template Generation ADR

---

packages/core/src/odata-common/request-builder/delete-request-builder-base.ts
packages/core/src/odata-common/request-builder/index.ts
packages/core/src/odata-v2/request-builder/delete-request-builder.ts
packages/core/src/odata-v4/request-builder/delete-request-builder.ts

Second PR for duplicated code reduction.
This one is about the delete request config.

chore: Reduce code duplication delete request builder

---

packages/core/src/odata-common/request-builder/index.ts
packages/core/src/odata-common/request-builder/update-request-builder-base.ts
packages/core/src/odata-v2/request-builder/update-request-builder.ts
packages/core/src/odata-v4/request-builder/update-request-builder.ts
test-packages/integration-tests/test/v2/change-detection-deep-update.spec.ts

Reduce code duplication for the update request builder.

chore: Reduce code duplication update request builder 

---

packages/core/src/header-util.ts

fix deprecated version

---

CONTRIBUTING.md

For new colleagues a little update on the E2E test package

chore: better onboarding

---

packages/core/test/request-builder/v4/function-import-request-builder.spec.ts
test-packages/type-tests/test/v4/action-imports.spec.ts

chore: add more function action import tests

---

knowledge-base/how-tos/remote-debugging.md

improve: remote debugging with space developer role

---

packages/openapi-generator/src/cli.ts

Mini-PR to refactor the error handling in the java runtime validation.

chore: Improve Java validation in openapi generator

---

knowledge-base/implementation-documentation/api-improvements.md

This is the documentation of our API improvement ideas. Please extend and improve the document for the upcoming discussions.

chore: Document API dicussions

---

packages/generator/README.md
packages/openapi-generator/README.md
packages/openapi-generator/package.json
packages/openapi-generator/src/index.ts
scripts/generate-test-services.ts

Adds a few sentences about what this is + installation and usage instructions.
I think our readmes could use some more love, but not on this PR.

chore: Improve OpenAPI generator readme

---

CHANGELOG.md
packages/openapi-generator/package.json

- remove the `private: true` in `package.json`
- add release notes

chore: prepare the openapi generator beta release

---

.reuse/dep5
test-packages/test-services/openapi/swagger-yaml-service/api.ts
test-packages/test-services/openapi/swagger-yaml-service/index.ts
test-packages/test-services/openapi/test-service/api.ts
test-packages/test-services/openapi/test-service/index.ts

This should fix all other PRs failing because of wrong test services

chore: Update copyright notice

---

CHANGELOG.md

Added new "rules" to changelog

chore: Add examples of tags to changelog

---

.github/workflows/api-docs.yml
.github/workflows/bump.yml

chore: fix permission in the bump workflow

---

packages/core/src/connectivity/scp-cf/destination/destination-accessor-authentication-type.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-accessor-provider-subscriber-lookup.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-accessor-types.ts

Added documentation on the ISS field so it is used in the right way hopefully.

chore: add documentation on iss

---

package.json
yarn.lock

chore: Resolve axios to 0.21.1 for all dependencies as well

---

CONTRIBUTING.md
STYLEGUIDE.md

This is the initial version of the style guide. Please take some time to read it. There are points, that we do not consistently fulfill and there might be points that you might not agree with. If there are any, let's talk about them.

chore: Styleguide

---

.github/workflows/release.yml
package.json

Generate test services after version bump.

chore: Fix test services on bump

---

packages/analytics/README.md
packages/cli/README.md
packages/core/README.md
packages/eslint-config/README.md
packages/generator/README.md
packages/openapi-generator/README.md
packages/test-util/README.md
packages/util/README.md
scripts/COMMON-README-PART.md
scripts/check-licenses.ts
scripts/replace-common-readme.ts

Update the eslint-config README.md to use the script that adds logo and additional info.

Update eslint config README

---

packages/generator/src/generator.spec.ts
packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/generator/src/sdk-metadata/sdk-metadata.spec.ts
scripts/generate-test-services.ts

This PR should fix the 3 failing tests on the [release build](https://github.com/SAP/cloud-sdk-js/runs/2146291094?check_suite_focus=true)
See comments below for details.

Fix release build

---

packages/core/src/connectivity/scp-cf/connectivity-service.spec.ts
packages/core/src/connectivity/scp-cf/csrf-token-header.ts
packages/core/src/odata-common/edm-types.ts
packages/core/src/odata-common/request-builder/batch/batch-response-deserializer.spec.ts
packages/generator/src/sdk-metadata/pregenerated-lib.ts
packages/openapi-generator/src/generator.ts
scripts/generate-docs.ts
test-resources/generator/resources/faulty-typescript/faulty-typescript.ts

This should finally fix all linter warnings and improve reviews. I also accidentally removed the doc generation before. Added it back...

chore: Fix lint problems that can only be fixed manually

---

package.json
yarn.lock

Dependabot could not resolve this, so I added a resolution.

chore: Manual security update

---

knowledge-base/adr/0018-openapi-generator.md
knowledge-base/adr/0019-openapi-generator-naming.md

Documentation of our decisions regarding OpenAPI naming.

chore: Add OpenAPI naming ADR

---

packages/core/test/test-util/test-services/openapi/test-service/schema/other-simple-test-entity.ts
packages/core/test/test-util/test-services/openapi/test-service/schema/simple-test-entity-with-symbols-1.ts
packages/core/test/test-util/test-services/openapi/test-service/schema/simple-test-entity-with-symbols.ts
packages/core/test/test-util/test-services/openapi/test-service/schema/simple-test-entity.ts
packages/core/test/test-util/test-services/openapi/test-service/schema/test-entity.ts
packages/openapi-generator/src/file-serializer/schema-file.spec.ts
packages/openapi-generator/src/file-serializer/schema-file.ts
test-packages/test-services/openapi/test-service/schema/other-simple-test-entity.d.ts
test-packages/test-services/openapi/test-service/schema/other-simple-test-entity.ts
test-packages/test-services/openapi/test-service/schema/simple-test-entity-with-symbols-1.d.ts
test-packages/test-services/openapi/test-service/schema/simple-test-entity-with-symbols-1.ts
test-packages/test-services/openapi/test-service/schema/simple-test-entity-with-symbols.d.ts
test-packages/test-services/openapi/test-service/schema/simple-test-entity-with-symbols.ts
test-packages/test-services/openapi/test-service/schema/simple-test-entity.d.ts
test-packages/test-services/openapi/test-service/schema/simple-test-entity.ts
test-packages/test-services/openapi/test-service/schema/test-entity.d.ts
test-packages/test-services/openapi/test-service/schema/test-entity.ts

Schemas referencing themselves should not import themselves.

fix: Fix self reference in schema

---

packages/openapi-generator/src/file-serializer/api-file.spec.ts
packages/openapi-generator/src/file-serializer/api-file.ts
packages/openapi-generator/src/schema-util.ts

Fix api file generation for files containing reference schemas in parameters

fix: Add imports for parameters in api files

---

packages/openapi-generator/src/file-serializer/api-file.ts
packages/openapi-generator/src/schema-util.spec.ts
packages/openapi-generator/src/schema-util.ts

I realized, that I forgot some things on the PR to get rid of `Exclude`...

chore: Remove unused functions

---

packages/core/src/http-client/http-client-types.ts

I added some docs for the interface HttpRequestOptions.

chore: update docs for http request options

---

packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/generator/src/sdk-metadata/generation-and-usage.ts
packages/generator/src/sdk-metadata/pregenerated-lib.ts
packages/generator/src/sdk-metadata/sdk-metadata-types.ts
packages/generator/src/sdk-metadata/sdk-metadata.spec.ts
packages/generator/src/sdk-metadata/sdk-metadata.ts

Added a bit more detailed generation steps and the field `serviceStatus` in the metadata.

chore: add generation steps

---

CHANGELOG.md

changed casing of some words + added info on different URL.

Update CHANGELOG.md for CSRF

---

packages/openapi-generator/src/parser/api.spec.ts
packages/openapi-generator/src/parser/api.ts
packages/openapi-generator/src/parser/document.spec.ts
packages/openapi-generator/src/parser/document.ts
packages/openapi-generator/src/parser/media-type.spec.ts
packages/openapi-generator/src/parser/media-type.ts
packages/openapi-generator/src/parser/operation.spec.ts
packages/openapi-generator/src/parser/operation.ts
packages/openapi-generator/src/parser/parsing-info.ts
packages/openapi-generator/src/parser/refs.spec.ts
packages/openapi-generator/src/parser/refs.ts
packages/openapi-generator/src/parser/request-body.spec.ts
packages/openapi-generator/src/parser/request-body.ts
packages/openapi-generator/src/parser/responses.spec.ts
packages/openapi-generator/src/parser/responses.ts
packages/openapi-generator/src/parser/schema.spec.ts
packages/openapi-generator/src/parser/schema.ts
packages/openapi-generator/src/schema-util.spec.ts
packages/openapi-generator/test/test-util.ts

Refactoring of the document referenced and schemarefmapping into one object.

Refactor references and schema mapping

---

packages/generator/internal.d.ts
packages/generator/internal.js
packages/generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap
packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/generator/src/sdk-metadata/generation-and-usage.spec.ts
packages/generator/src/sdk-metadata/generation-and-usage.ts
packages/generator/src/sdk-metadata/index.ts
packages/generator/src/sdk-metadata/links.spec.ts
packages/generator/src/sdk-metadata/links.ts
packages/generator/src/sdk-metadata/pregenerated-lib.spec.ts
packages/generator/src/sdk-metadata/pregenerated-lib.ts
packages/generator/src/sdk-metadata/sdk-metadata-types.ts
packages/generator/src/sdk-metadata/sdk-metadata.spec.ts
packages/generator/src/sdk-metadata/sdk-metadata.ts
packages/test-util/src/url.spec.ts
packages/test-util/src/url.ts

Adjust the metadata after the UI discussion.

Metadata adjustments

---

packages/openapi-generator/README.md
packages/openapi-generator/src/cli/index.ts
packages/openapi-generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap
packages/openapi-generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/openapi-generator/src/sdk-metadata/generation-and-usage.ts

Rename the generator command to `openapi-generator`

chore: Rename generator command

---

packages/openapi-generator/README.md
packages/openapi-generator/package.json
packages/openapi-generator/src/cli/index.ts
packages/openapi-generator/src/file-writer/create-file.spec.ts
packages/openapi-generator/src/file-writer/create-file.ts
packages/openapi-generator/src/generator.spec.ts
packages/openapi-generator/src/generator.ts
packages/openapi-generator/src/options/generator-options.spec.ts
packages/openapi-generator/src/options/generator-options.ts

This PR adds an `overwrite` option, so that by default files will not be overwritten.

feat: Add overwrite option

---

packages/openapi-generator/README.md

chore: remove the "beta" from openapi readme.

---

knowledge-base/adr/0021-odata-url-builder.md

chore: add ADR for OData url builder

---

packages/generator/src/name-formatting-strategies.ts

Fix this: warning https://github.com/SAP/cloud-sdk-js/security/code-scanning/152?query=ref%3Arefs%2Fheads%2Fmain

chore: Fix potential polynomial redos

---

packages/openapi-generator/README.md

fix: readme of openapi package

---

CHANGELOG.md
packages/core/package.json
packages/core/src/connectivity/scp-cf/destination/circuit-breaker.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-service.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-service.ts
packages/core/src/connectivity/scp-cf/resilience-options.ts
packages/core/src/connectivity/scp-cf/xsuaa-service.spec.ts
packages/core/src/connectivity/scp-cf/xsuaa-service.ts
packages/core/test/test-util/environment-mocks.ts
yarn.lock

The circuit breaker was basically unused. This PR fixes that and add tests to ensure this does not happen again.

Fix: Re-enable circuit breaker

---

packages/analytics/package.json
packages/core/package.json
packages/generator-common/package.json
packages/generator/package.json
packages/openapi-generator/package.json
packages/test-util/package.json
packages/util/package.json
test-packages/e2e-tests/package.json
test-packages/integration-tests/package.json
test-resources/cli/nest/package.json

This simplifies the test scripts to be just "test" and removes debug test scripts as they are not necessary anymore

chore: Reduce test scripts

---

packages/generator-common/src/sdk-metadata/sdk-metadata-types.ts
packages/generator-common/src/sdk-metadata/sdk-metadata.ts
packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/generator/src/sdk-metadata/generation-and-usage.ts
packages/openapi-generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/openapi-generator/src/sdk-metadata/generation-and-usage.ts

Adjust the service status object and introduce two helper functions used in the api mirrow.

chore: adjust metadata service status

---

packages/generator-common/src/sdk-metadata/generation-and-usage.ts
packages/generator-common/src/sdk-metadata/sdk-metadata-types.ts
packages/generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap
packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/generator/src/sdk-metadata/generation-and-usage.ts
packages/openapi-generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap
packages/openapi-generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/openapi-generator/src/sdk-metadata/generation-and-usage.ts

add a new header field to the metadata.

chore: add header to metadata

---

packages/core/src/odata-common/selectable/legacy/any-field.ts
packages/core/src/odata-common/selectable/legacy/big-number-field.ts
packages/core/src/odata-common/selectable/legacy/binary-field.ts
packages/core/src/odata-common/selectable/legacy/boolean-field.ts
packages/core/src/odata-common/selectable/legacy/date-field.ts
packages/core/src/odata-common/selectable/legacy/duration-field.ts
packages/core/src/odata-common/selectable/legacy/enum-field.ts
packages/core/src/odata-common/selectable/legacy/number-field.ts
packages/core/src/odata-common/selectable/legacy/string-field.ts
packages/core/src/odata-common/selectable/legacy/time-field.ts

This PR fixes the incorrect deprecation notes introduced by #1408.

chore: Fix incorrect deprecation notes

---

packages/core/src/connectivity/scp-cf/authorization-header.ts

chore: explicitly mention the SAP Cloud SDK in the log

---

.github/workflows/fosstars-report.yml
README.md

This PR adds a badge to the Readme file.

chore: add fosstars badge

---

README.md
test-resources/odata-service-specs/v4/service-mapping.json

Close: https://github.com/SAP/cloud-sdk-js/issues/1468

fix: reuse reference

---

README.md

This PR adds a note to the license section in the readme.
It makes it more transparent, that we have some dependencies, that are free, but not Open Source.

chore: Update license information

---

LICENSES/Apache-2.0.txt

chore: update copyright

---

package.json

Fix vulnerable dev dependency.

chore: Fix dependency

---

packages/core/src/connectivity/scp-cf/index.ts
packages/core/src/connectivity/scp-cf/user.ts

Closes SAP/cloud-sdk-backlog#40
@jjtang1985 @marikaner Should the generated docs be checked in as well? There are quite a lot of changes as some dependencies have changed and references to dependency types now have changes throughout the docs.

chore: Add docs for user interface and export the interface

---

README.md

Closes SAP/cloud-sdk-backlog#209

Announce upgrade strategy in README.md

---

packages/core/src/connectivity/scp-cf/destination/destination-accessor-authentication-type.spec.ts
packages/core/src/odata-v2/payload-value-converter.ts

This most likely is not an actual problem for the SDK, but I think the new regex reads nicer anyways.

chore: Fix ReDos vulnerability

---

knowledge-base/how-tos/0006-set-up-identity-service.md

The doc shows how to call the token endpoint for the following grant types: 
- client credential grant
- password grant

doc: verify IAS token via http requests

---

packages/analytics/package.json
packages/analytics/src/usage-analytics.spec.ts
packages/core/src/connectivity/scp-cf/connectivity-service-types.ts
packages/core/src/connectivity/scp-cf/connectivity-service.ts
packages/core/src/connectivity/scp-cf/jwt.ts

Clean up some code I came across. The multiple `then()` and other chained methods are not good to read.

chore: A small refactoring 

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

New section about providing impact/priority information are added to the templates.

chore: add impact/priority section to the templates

---

CHANGELOG.md
packages/generator-common/src/compiler.spec.ts
packages/generator-common/src/compiler.ts

I needed this options in an other project where I wanted to exclude files trom the transpilation.

chore: add include/exclude to transpile directory

---

knowledge-base/adr/0027-versioning-strategy.md
yarn.lock

Closes SAP/cloud-sdk-backlog#19
This is a first discussion basis for the meeting and will be polished after discussion.

Versioning Strategy

---

packages/odata-common/src/index.ts
packages/odata-common/src/request-builder/delete-request-builder-base.ts
packages/odata-common/src/request-builder/request-builder-base.ts
packages/odata-v2/src/request-builder/delete-request-builder.ts
packages/odata-v4/src/request-builder/delete-request-builder.ts

chore: I forgot to remove one base re-export.

chore: remove last base builder

---

packages/connectivity/src/scp-cf/destination/destination-accessor-provider-subscriber-lookup.spec.ts
packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts
packages/connectivity/src/scp-cf/destination/destination-from-service.ts
packages/core/test/test-util/mocked-access-tokens.ts

transfer the content of #1769 to 2.0.

chore: transfer #1769 to 2.0

---

CHANGELOG.md
packages/odata-common/src/request-builder/batch/batch-response-parser.spec.ts
packages/odata-common/src/request-builder/batch/batch-response-parser.ts

Closes SAP/cloud-sdk-backlog#413
Merge #1763 to 2.0

fix: batch DELETE response error

---

CHANGELOG-v2.md

Adds the changelog for the merged PR #1764 

refractor: add changelog

---

knowledge-base/adr/0028-public-api-extraction.md

Adjust the existing ADR as a consequence on our discussion.

chore: adjust export strategy

---

packages/odata-common/src/index.ts
packages/odata-common/src/payload-value-converter.ts
packages/odata-common/src/request/odata-get-by-key-request-config.spec.ts
packages/odata-common/src/uri-conversion/odata-uri.ts
packages/odata-common/src/uri-conversion/uri-value-converter.ts
packages/odata-v2/src/index.ts
packages/odata-v2/src/payload-value-converter.ts
packages/odata-v2/src/request-builder/get-all-request-builder.ts
packages/odata-v2/src/uri-conversion/odata-uri.ts
packages/odata-v2/src/uri-conversion/uri-value-converter.ts
packages/odata-v4/src/index.ts
packages/odata-v4/src/payload-value-converter.ts
packages/odata-v4/src/request-builder/get-all-request-builder.ts
packages/odata-v4/src/uri-conversion/odata-uri.ts
packages/odata-v4/src/uri-conversion/uri-value-converter.ts
test-resources/test/test-util/request-mocker.ts

In the PR #1766  @jjtang1985 requested that some code was remade this PR increases the reuse and should minimize the reimplementations.

chore: increase code reuse

---

packages/connectivity/src/scp-cf/client-credentials-token-cache.spec.ts
packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts
packages/connectivity/src/scp-cf/destination/destination-cache.ts

fix: Overwrite default expiration times (#1771)

---

scripts/check-public-api.spec.ts
scripts/check-public-api.ts

Follow up on #1823. Improve code in compareBarrels.

chore: update compareBarrels method

---

CHANGELOG.md
knowledge-base/how-tos/0005-how-to-execute-auth-flow-tests.md
packages/core/src/connectivity/scp-cf/destination/destination-accessor-authentication-type.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-accessor-failure-cases.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts
packages/core/src/connectivity/scp-cf/destination/destination-service-cache.spec.ts
packages/core/src/connectivity/scp-cf/destination/destination-service.ts
packages/core/src/connectivity/scp-cf/destination/destination.ts
packages/core/src/odata-v2/request-builder/get-all-request-builder.spec.ts
packages/core/src/openapi/openapi-request-builder.spec.ts
packages/core/test/test-util/destination-service-mocks.ts
packages/core/test/test-util/example-destination-service-responses.ts
test-packages/integration-tests/test/auth-flows/auth-flow-util.ts
test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts

apply the changes from #1845 . I tested the auth-flow tests and they worked.

fix: Missing x user token header

---

packages/http-client/src/csrf-token-header.spec.ts
packages/odata-common/src/filter/filter-functions.ts
packages/odata-v2/src/filter-functions.ts
packages/odata-v4/src/filter-functions.ts
test-resources/test/test-util/filter-factory.ts

This PR fixes the failing tests of filter function

fix: filter function (deserialiser)

---

packages/odata-v2/package.json

The issue still exists and revert the commit.

Revert "test: use fixed version for internal dependencies"

---

packages/connectivity/README.md
packages/eslint-config/README.md
packages/generator-common/README.md
packages/generator/README.md
packages/http-client/README.md
packages/odata-common/README.md
packages/odata-v2/README.md
packages/odata-v4/README.md
packages/openapi-generator/README.md
packages/openapi/README.md
packages/test-util/README.md
packages/util/README.md
scripts/COMMON-README-PART.md

Follow up from a previous PR. Update common readme text to use 'GitHub' as the correct spelling.

chore: Update common readme text

---

packages/odata-v2/README.md

fix: fix typo in odata-v2 readme 

---

packages/connectivity/README.md
packages/eslint-config/README.md
packages/generator-common/README.md
packages/generator/README.md
packages/http-client/README.md
packages/odata-common/README.md
packages/odata-v2/README.md
packages/odata-v4/README.md
packages/openapi-generator/README.md
packages/openapi/README.md
packages/test-util/README.md
packages/util/README.md
scripts/COMMON-README-PART.md

This is a cherry pick from #1978.

fix: wrong support link (#1978)

---

packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts

This ticket cleans up a test I encountered

fix: Remove code duplication

---

package.json
yarn.lock

Cherry pick @jjtang1985 fix for dot-prop issue.

chore: Cherry pick fix dot prop esm issue

---

packages/odata-common/package.json
packages/odata-v2/package.json

I coincidentally saw this weird check and removed the self-ignoring checks.

chore: Fix weird dependency checks

---

.github/workflows/codeql-analysis.yml
.github/workflows/codeql-config.yml

The code ql was missing for 1.0.

chore: enable code ql for 1.0

---

packages/generator/src/edmx-parser/common/edmx-parser.ts
packages/generator/src/edmx-to-vdm/common/action-function-return-types.ts
packages/generator/src/edmx-to-vdm/common/entity.ts
packages/generator/src/edmx-to-vdm/v4/action-import.spec.ts
packages/generator/src/edmx-to-vdm/v4/entity.spec.ts

Removed the if statement after testing all S/4 Cloud and OP oData services with the latest version of the generator.

chore: fix todo 1584

---

README.md
packages/odata-v4/README.md

Closes SAP/cloud-sdk-backlog#566.
Updated root readme to include:
- new packages
- release announcement and upgrade guide link
- sample projects section and cli deprecation

fix: update root readme

---

test-packages/e2e-tests/package.json
yarn.lock

This PR updates the dependency in the package.json (which was already updated in the yarn.lock by another PR)

chore: update dependency in package.json

---

packages/generator-common/src/compiler.spec.ts
packages/openapi-generator/src/options/generator-options.spec.ts

This PR fixes the windows tests on 1.0 main branch

fix: fix windows test on 1.0-main

---

packages/core/postinstall.js

relates to SAP/cloud-sdk-backlog#485
update the postinstall message once the version 2.0 is released.

chore: Update postinstall

---

CHANGELOG.md
packages/odata-common/src/de-serializers/uri-value-converter.ts
packages/odata-common/src/uri-conversion/get-resource-path.ts
packages/odata-v2/src/request-builder/get-by-key-request-builder.spec.ts
packages/odata-v2/src/uri-conversion/get-resource-path.spec.ts
test-packages/integration-tests/test/v2/request-builder.spec.ts

Closes SAP/cloud-sdk-backlog#548.

fix: fix url encoding in getByKey

---

CHANGELOG.md

Post install is mentioned in the release notes

chore: add release notes for version 1

---

.github/workflows/release.yml

Fix: publish v1

---

knowledge-base/implementation-documentation/0010-release-version-1-vdm.md
knowledge-base/implementation-documentation/0010-release-version-1-vdms.md

This PR contains the alignment of potential v1 vdm release.

chore: add doc about v1 vdm release

---

packages/connectivity/src/scp-cf/connectivity-service-types.ts
packages/connectivity/src/scp-cf/destination/destination-accessor.ts
packages/connectivity/src/scp-cf/destination/destination-from-service.ts
packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts
packages/odata-v2/src/de-serializers/entity-deserializer.ts
packages/odata-v2/src/filter-functions.ts
packages/odata-v4/src/de-serializers/entity-deserializer.ts
packages/odata-v4/src/filter-functions.ts
packages/openapi/src/openapi-request-builder.ts
packages/util/src/logger/format/local.ts
scripts/check-public-api.ts

Fixing some doc comments.
Relates to SAP/cloud-sdk-backlog#580.

chore: Fix some doc comments

---

CHANGELOG.md

Closes SAP/cloud-sdk-backlog#649.
Release dates for 2.0.0, 2.1.0, 2.2.0 are updated.

docs: update CHANGELOG.md with release date

---

scripts/npm-stats.ts

I missed some comments in the last review. Those are the requested improvements. I did not add any pushing to a different repository, because it is out of scope in my opinion and should be a follow up if necessary.

chore: Improve stats script

---

packages/generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap
packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap
packages/generator/src/sdk-metadata/code-samples.ts

Closes SAP/cloud-sdk-backlog#673.
Fixed formatting on APIHub of our code snippet example.

chore: fix code snippet formatting issues

---

knowledge-base/adr/0031-resilience-options.md
knowledge-base/adr/0031-resilience.js
packages/connectivity/src/scp-cf/environment-accessor-types.ts

As in the title, I added some executable PoC style examples for better understanding of resilience in SAP Cloud SDK for JS.

chore: Add some examples for resilience

---

packages/connectivity/src/http-agent/http-agent.ts
packages/connectivity/src/scp-cf/destination/destination-from-service.ts
packages/connectivity/src/scp-cf/destination/destination-service.ts
packages/generator/src/sdk-metadata/generation-and-usage.spec.ts

Fix the tests for node 16 which needed the full path and fixed a few linter warnings.

Fix node 16 & 18 error 

---

scripts/npm-stats.ts

fix: typo of npm-stats.ts

---

knowledge-base/adr/0029-custome-header-handling.md

The original ADR was outdated and needs some updates.

chore: update custom header ADR

---

.changeset/soft-mugs-drum.md
packages/odata-v2/src/de-serializers/converters.spec.ts
packages/odata-v2/src/de-serializers/converters.ts

Relates to: #2589 
Add support for negative timestamps before 1970-01-01.

fix: add negative timestamp support

---

scripts/npm-stats.ts

The current downloads action fails. I hopefully fixed it and improved the output a bit:
```
@sap-cloud-sdk/util:
- v1: 139809 downloads
- v2: 4687 downloads
@sap-cloud-sdk/connectivity:
- v2: 4019 downloads
@sap-cloud-sdk/http-client:
- v2: 3874 downloads
@sap-cloud-sdk/odata-v2:
- v2: 656 downloads
@sap-cloud-sdk/odata-v4:
- v2: 329 downloads
@sap-cloud-sdk/generator:
- v1: 465 downloads
- v2: 262 downloads
@sap-cloud-sdk/openapi:
- v2: 269 downloads
@sap-cloud-sdk/openapi-generator:
- v1: 80 downloads
- v2: 226 downloads
@sap-cloud-sdk/test-util:
- v1: 521 downloads
- v2: 278 downloads
@sap-cloud-sdk/eslint-config:
- v1: 109 downloads
- v2: 65 downloads
@sap-cloud-sdk/temporal-de-serializers:
- v2: 15 downloads
@sap-cloud-sdk/odata-common:
- v2: 711 downloads
@sap/cds:
- v1: 106 …
```

chore: Improve downloads script

---

.github/dependabot.yml

This introduces dependabot for GH Actions

Update GH Actions through dependabot

---

.github/workflows/release.yml
scripts/add-changelog.ts

The path needs to be adjusted to match the new folder structure in the docs repo.

fix: adjust path

---

.github/workflows/blackduck.yml
.github/workflows/build.yml
.github/workflows/downloads.yml
.github/workflows/memory-tests.yml
packages/odata-v2/src/request-builder/update-request-builder.spec.ts

It should be safe to not ignore the engines anymore as edm converters lifted their restriction.
UPDATE: Except for the build.

Stop ignoring engines

---

package.json

chore: Make puppeteer a dev dependency

---

packages/generator/src/sdk-metadata/generation-and-usage.spec.ts
packages/openapi-generator/src/sdk-metadata/generation-and-usage.spec.ts
test-packages/e2e-tests/test/metadata.spec.ts

The complete clean up will happen [here](https://github.com/SAP/cloud-sdk-backlog/issues/620).

chore: disable metadata e2e tests

---

.changeset/2.0-fix.md
packages/mail-client/CHANGELOG.md
scripts/after-bump.ts

Fixes a few typos in the changelogs.

fix: CHANGELOG typos

---

.changeset/patch-mail.md

The release build needs changeset for deciding whether patch or minor is applied.

chore: add changeset

---

.changeset/happy-bears-hide.md

Forgot to check in the compability note for #2775

chore: add compatibility note for  #2775 

---

knowledge-base/adr/0033-send-email.md
packages/mail-client/README.md
packages/mail-client/src/mail-client.ts
test-packages/e2e-tests/test/mail/mail.spec.ts
test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts

This PR does the following:
- ADR updates
- clean up comments
- update tests

chore: update mail ADR

---

packages/odata-v2/src/request-builder/batch-request-builder.spec.ts
test-packages/e2e-tests/test/TripPin/request-builder.spec.ts

As in the title. Just came accross this accidentally.

chore: Fix typos

---

package.json
packages/mail-client/src/index.ts
scripts/npm-stats.ts

This PR fixes the package name and the readme of the api doc.

fix: mail api doc

---

packages/odata-v2/src/request-builder/delete-request-builder.ts
packages/odata-v4/src/request-builder/delete-request-builder.ts

I found this accidentally and believe this is a typo.
Changelog is still missing.

Fix: Fix type in delete request builder

---

.github/workflows/lint.yml

add workflow

---

.github/workflows/lint.yml
packages/odata-v2/src/edm-types.ts

Closes SAP/cloud-sdk-backlog#717.
Add a workflow to run the linting on a given branch. Made some tests and for example this commit:
https://github.com/SAP/cloud-sdk-js/pull/2952/commits/ab4a0c4ae9f887e6a87a94473e408e373b7be2f7
was created from the workflow.

Lint workflow 2

---

README.md
packages/connectivity/README.md
packages/eslint-config/README.md
packages/generator-common/README.md
packages/generator/README.md
packages/http-client/README.md
packages/mail-client/README.md
packages/odata-common/README.md
packages/odata-v2/README.md
packages/odata-v4/README.md
packages/openapi-generator/README.md
packages/openapi/README.md
packages/temporal-de-serializers/README.md
packages/test-util/README.md
packages/util/README.md
scripts/COMMON-README-PART.md

Add the sample repo link to both GitHub readme and npm readme.

chore: add sample repo links

---

.changeset/del-request-builder-type.md
.changeset/generator-common-err-msg.md
.changeset/open-api-generator-force-option.md

The following PRs missed the release notes:
- https://github.com/SAP/cloud-sdk-js/pull/2891
- https://github.com/SAP/cloud-sdk-js/pull/2898
- https://github.com/SAP/cloud-sdk-js/pull/2918

chore: add missing release notes

---

packages/generator/.changeset/kind-planes-float.md
packages/generator/src/reserved-words.ts
packages/generator/src/service-name-formatter.spec.ts

Co-authored-by: Yuan Zhuang <yuan.zhuang@sap.com>
Co-authored-by: Deeksha Sinha <88374536+deekshas8@users.noreply.github.com>
Closes SAP/cloud-sdk-backlog#953.

Fix formatting bug (#3058)

---

.github/PULL_REQUEST_TEMPLATE.md

See also https://github.com/SAP/cloud-sdk-js/pull/3082

Add v3 development specific info to PR template

---

package.json
packages/connectivity/src/scp-cf/cache.spec.ts
packages/connectivity/src/scp-cf/client-credentials-token-cache.spec.ts
packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts
packages/connectivity/src/scp-cf/destination/destination-from-registration.spec.ts
yarn.lock

chore: Update types/jest to same major version as jest

---

.changeset/beige-rocks-compare.md
.changeset/clever-apes-know.md
.changeset/giant-hounds-sleep.md
.changeset/kind-planes-float.md
.changeset/spotty-boats-kiss.md
.changeset/strange-schools-heal.md
.changeset/swift-eyes-turn.md
.changeset/witty-snails-behave.md

chore: Fix changeset tags

---

.changeset/khaki-cooks-enjoy.md
.changeset/kind-planes-float.md

chore: Fix some changeset prefixes

---

.github/workflows/next-build-nightly.yml

Fix the syntax of the pipeline.

chore: Fix nightly build

---

packages/connectivity/src/scp-cf/destination/destination-accessor-types.ts
packages/connectivity/src/scp-cf/destination/destination-accessor.ts
packages/connectivity/src/scp-cf/destination/destination-cache.ts
packages/connectivity/src/scp-cf/destination/destination-from-registration.ts
packages/connectivity/src/scp-cf/destination/destination-from-service.ts
packages/connectivity/src/scp-cf/destination/destination-service-types.ts
packages/connectivity/src/scp-cf/destination/destination-service.ts
packages/connectivity/src/scp-cf/destination/destination.ts

As in the title, have fun reading ;)

chore: Fix typos in the connectivity package

---

packages/odata-common/CHANGELOG.md
packages/odata-common/src/batch-response.ts
packages/odata-common/src/de-serializers/de-serializers.ts
packages/odata-common/src/entity-base.ts
packages/odata-common/src/filter/boolean-filter-function.ts
packages/odata-common/src/filter/unary-filter.ts
packages/odata-common/src/request-builder/action-function-import-request-builder-base.ts
packages/odata-common/src/request-builder/batch/batch-request-serializer.ts
packages/odata-common/src/request-builder/batch/batch-response-parser.ts
packages/odata-common/src/request-builder/create-request-builder-base.ts
packages/odata-common/src/request-builder/delete-request-builder-base.ts
packages/odata-common/src/request-builder/get-by-key-request-builder-base.ts
packages/odata-common/src/request-builder/update-request-builder-base.ts
packages/odata-common/src/request/odata-request-traits.ts
packages/odata-v2/src/de-serializers/converters.ts
packages/odata-v2/src/request-builder/batch-request-builder.spec.ts
packages/odata-v2/src/selectable/oderable.spec.ts
packages/odata-v2/src/uri-conversion/odata-uri.spec.ts
packages/openapi/src/openapi-request-builder.spec.ts

chore: Fix typos in OData and OpenAPI packages

---

.github/actions/check-pr/index.js
build-packages/check-pr/index.ts

Remove check for title case in PRs.

chore: remove case check

---

.changeset/orange-queens-explode.md

There are no other changes on this branch, therefore adding a changeset.
Closes SAP/cloud-sdk-backlog#1018.

chore: Add changeset for security update

---

.changeset/odata-v2-update-string-null.md

Just a minor formatting issue that was applied to the main branch previously.

chore: Improve markdown formatting in changelog

---

.changeset/sour-ravens-join.md
packages/connectivity/src/scp-cf/connectivity-service.ts
packages/connectivity/src/scp-cf/destination/destination-accessor-authentication-type.spec.ts
packages/connectivity/src/scp-cf/destination/destination-from-service.ts
test-packages/integration-tests/test/auth-flows/auth-flow-util.ts
test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts

relates to https://github.com/SAP/cloud-sdk-js/issues/3349
Just cherry pick the fix from version 3 fix see #3351

fix: Fix ISS for OnPremise Basic

---

.github/actions/get-changelog/index.js

Not sure why this was not done in https://github.com/SAP/cloud-sdk-js/pull/3384

chore: Update compiled code of github action

---

.changeset/loud-starfishes-type.md

Leftover https://github.com/SAP/cloud-sdk-js/pull/3308 due to automerge.

chore: Reword changeset to improve it

---

README.md

chore: Update README for version 3

---

.changeset/smart-phones-act.md
packages/generator-common/src/options-per-service.spec.ts
packages/generator-common/src/options-per-service.ts
packages/generator-common/src/util.ts

I noticed that we missed this minor issue when changing the options per service behavior.

chore: Improve logging for package name generation

---

packages/mail-client/README.md

chore: Remove experimental from mail-client readme

---

README.md

chore: fix broken link in toc

---

packages/connectivity/src/scp-cf/destination/destination-accessor-authentication-type.spec.ts
packages/connectivity/src/scp-cf/destination/destination-accessor-failure-cases.spec.ts
packages/connectivity/src/scp-cf/destination/destination-accessor-provider-subscriber-lookup.spec.ts
packages/connectivity/src/scp-cf/destination/destination-accessor-proxy-configuration.spec.ts
packages/connectivity/src/scp-cf/destination/destination-accessor.ts
packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts
packages/connectivity/src/scp-cf/destination/destination-from-service.ts
packages/connectivity/src/scp-cf/identity-service.spec.ts
packages/connectivity/src/scp-cf/identity-service.ts
packages/http-client/src/http-client.spec.ts

Refactor token exchange and do not exchange tokens that are issued by XSUAA.

chore: Refactor token exchange

---

packages/connectivity/src/scp-cf/destination/destination-from-service.ts

Change origin to `'provider'` in `getProviderDestinationCache()`

chore: Change origin to provider

---

.changeset/wet-chairs-enjoy.md
packages/odata-common/src/request-builder/batch/__snapshots__/batch-request-serializer.spec.ts.snap
packages/odata-common/src/request-builder/batch/batch-request-options.ts
packages/odata-common/src/request-builder/batch/batch-request-serializer.spec.ts
packages/odata-common/src/request-builder/batch/batch-request-serializer.ts

fix: add relativeToRequestURI BatchSubRequestPathType

---

.github/workflows/auto-lint.yml

skips the auto linting for forks

chore: fix autofix

---

packages/mail-client/src/mail-client-types.ts

Adding this option should help log the nodemailer logs to console and help in debugging.

chore: Add logger option to log to console

---

.changeset/tender-planets-notice.md

Adds Improvement changelog entry for `logger` option in mail-client

chore: Add changelog for new mail-client option

---

.changeset/fifty-clouds-turn.md
packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts
packages/connectivity/src/scp-cf/destination/service-binding-to-destination.ts

* If applicable:
I included an update of the documentation together with the [Java SDK Update here](https://github.com/SAP/cloud-sdk/pull/1741).
Compare the similar update to the Java SDK [here](https://github.com/SAP/cloud-sdk-java/pull/358).

feat: Support AI Core Service Binding

---

packages/connectivity/src/scp-cf/environment-accessor/service-credentials.ts
packages/connectivity/src/scp-cf/environment-accessor/xsuaa.ts

Revert "chore: improve error handling"

---

.github/workflows/build.yml
packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts

Fixing everything, input + output + making the canary build a bit simpler

chore: fix PR workflows + canary build

---

.changeset/fifty-clouds-turn.md

fix: Add message type in changeset file

---

packages/connectivity/package.json
packages/generator-common/package.json
packages/generator/package.json
packages/http-client/package.json
packages/mail-client/package.json
packages/odata-common/package.json
packages/odata-v2/package.json
packages/odata-v4/package.json
packages/openapi-generator/package.json
packages/openapi/package.json
packages/resilience/package.json
packages/temporal-de-serializers/package.json
packages/test-util/package.json
packages/util/package.json
test-packages/e2e-tests/package.json
test-packages/integration-tests/package.json
test-packages/self-tests/package.json
test-packages/test-services-e2e/package.json
test-packages/test-services-odata-common/package.json
test-packages/test-services-odata-v2/package.json
test-packages/test-services-odata-v4/package.json
test-packages/test-services-openapi/package.json
test-packages/type-tests/package.json

Fixes a typo in the prettier command

chore: fix typo

---

.changeset/curvy-carpets-talk.md
.changeset/light-insects-bow.md

chore: Fix types in changelog files

---

packages/connectivity/src/scp-cf/xsuaa-service.ts

Our e2e tests found that there is another problem with how we use the new xssec API. Reading the docs helps ;)

chore: fix xssec usage

---

packages/connectivity/src/scp-cf/destination/destination-service.ts
packages/resilience/src/retry.ts

Add more information about the original error in case of retry failure.

chore: Add error with cause for retry

---

.changeset/long-rivers-wait.md

chore: Update long-rivers-wait.md

---

packages/openapi/src/openapi-request-builder.ts

This makes certain fields/ methods protected so they can be accessed within the subclass in sap-ai-sdk.

chore: Change modifier to protected

---

packages/openapi/src/openapi-request-builder.ts

Revert access modifier for _fetchCsrfToken in OpenAPi req Builder

chore: Revert access modifier for _fetchCsrfToken in OpenAPi req Builder

---

packages/openapi-generator/src/parser/schema.spec.ts

the individual PRs merged yesterday were green, not sure why this was not detected.

chore: Fix schema nullable tests

---

CONTRIBUTING.md

AI/gen-ai-hub-sdk-js-backlog#140.
Reference GenAI contribution guidelines as requested by OSPO.

chore: Reference GenAI contribution guidelines

---

CHANGELOG.md

chore: Add the req newline in Changelog

---

packages/mail-client/src/mail-client.spec.ts
packages/mail-client/src/mail-client.ts
yarn.lock

Fixes the accidentally merged incorrect state of #5079

chore: fix order of things

---

.github/actions/changesets-fixed-version-bump/index.js
yarn.lock

Should address https://github.com/SAP/cloud-sdk-js/security/dependabot/68
The pm2 lib depends on pm2/agent ~2.0.0 (transitive dep) which in yarn lock resolved to 2.0.3. This version had the vulnerable ws@7.5.9. A newer version of pm2/agent was available with the fixed ws version but yarn does not automatically update transitive dependencies.

chore: Update ws

---

.github/actions/check-public-api/index.js

Update the bundled service in GH action for public api check

chore: Update service check-public-api

---

.changeset/chilled-colts-heal.md
.github/actions/check-public-api/index.js
packages/generator-common/src/compiler.ts

Adding node16 option as well to allow esm compilation

chore: Add node16 option

---

packages/mail-client/README.md

Relates https://github.com/SAP/ai-sdk-js-backlog/issues/169

chore: Add deprecation note for mail client

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/bump.yml
.github/workflows/release.yml

Adjusting workflows for v3 builds and releases.

chore: setup pipelines for v3-main

---

.github/workflows/auto-dependabot-fix.yml

Automatically fixes dependency issues of dependabot PRs by re-compiling and committing any potential diff.
Part of SAP/cloud-sdk-backlog#1260.

chore: Add dependabot automation

---

packages/mail-client/README.md

Related documentation PR: https://github.com/SAP/cloud-sdk/pull/1984/files

chore: Update mail client deprecation notes

---

.github/workflows/next-build-nightly.yml

fix: Pre-check in next-build-nightly

---

.github/actions/merge-and-write-changelogs/index.js
README.md
build-packages/merge-and-write-changelogs/index.ts

This PR builds the github action we've previously modified, but not rebuild.
Also updates an outdated readme.

chore: Build GitHub Action

---

.github/workflows/build.yml

Relates to SAP/ai-sdk-js-backlog#221.

chore: Improve GH actions

---

knowledge-base/how-tos/README.md

Add a readme file for the "how-tos" directory.

chore: Add readme for how-tos
