SAP/cloud-sdk-js

CHANGELOG.md, package-lock.json, packages/generator/src/generator-options.ts, packages/generator/src/generator.ts, packages/generator/test/generator-cli.spec.ts
Currently, a VDM package that contains a `package.json` with the same version as the `generator`. However, as a user, if the generated VDMs are the same, I don't really care whether I'm using `generator` `v1.0.0` or `v3.0.0`.
Also, without this change, it will force the `generator` and the `VDM` repo keep the same version forever.
=> Specify the package version of the generated VDMs from the generator CLI parameters.

.github/workflows/build.yml, packages/generator/src/aggregator-package/package-json.ts, packages/generator/src/generator.ts, packages/generator/src/service/package-json.ts, packages/generator/test/aggregator-package/package-json.spec.ts, packages/generator/test/generator-cli.spec.ts
In the generated `package.json`, there are two versions that share the same value:
- version of the package
- sdk dependency version
However, this is not correct.
The version of the package can be set from the CLI or as default, use the generator version.
The sdk dependancy should always be the same as the generator version.
=> Fix sdk dependency version in generated package json

.github/workflows/build.yml
`lerna publish --canary` creates a version based on the changes that it finds from git. If there are no changes with `--forcePublish` it will try to publish a version that already exists, causing the command to fail.
While I don't agree with this behaviour of `lerna`, I also think we don't need to publish new canary versions, when there are no changes in the packages.
=> Remove `forcePublish` flag for canary release

.gitignore, packages/analytics/package-lock.json, packages/core/package-lock.json, packages/generator/package-lock.json, packages/test-util/package-lock.json, packages/util/package-lock.json, test-packages/integration-tests/package-lock.json, test-packages/type-tests/package-lock.json
`lerna version` requires the `package-lock.json` files of the sub packages to be there. As I don't see a good reason to not have them, let's remove them from the `.gitignore`.
=> chore: Do not ignore the package-locks of sub packages

packages/core/README.md, packages/generator/README.md, packages/test-util/README.md, packages/util/README.md
These readme files are shown in the npmjs for all packages.
Will add the proper links when the example project is tested with this repo.
=> Remove wrong example links

packages/core/src/scp-cf/destination-accessor.ts, packages/core/src/scp-cf/vcap-service-destination.ts
This is not the first time that users get confused by the warnings produced by the "three-trier destination loading logic". We already adapted one of the error messages, but missed a different one. I now moved the "XF disclaimer" to a central place.
=> fix: Make warning less confusing (hopefully)

generate-test-services.ts, package-lock.json
For some reason the `generate-test-service` had an issue with the promisified `fs` methods. This issue is most likely related to the large dependency updated being merged this morning.
When I merged master I came across the issue. So to reproduce the problem just checkout master and run the `generate:test-services` task.
I added the explicit types and the compiler was happy again. Also we should consider running the `npm run generate:test-services` in the pipeline so that we always have the latest version in the repo and find this kind of errors in the future.
=> Fix: Dependency updates broke the generate test entity 

test-packages/integration-tests/jest.config.js
As discussed, this ignores the proxy test due to flakyness. We will take care of this next week and try to provide an appropriate fix.
=> chore: Ignore proxy test until next week

package-lock.json, packages/core/src/scp-cf/destination-accessor.ts, packages/core/src/scp-cf/destination.ts, packages/core/src/scp-cf/env-destination-accessor.ts, packages/core/test/request-builder/get-all-request-builder.spec.ts, packages/core/test/scp-cf/__snapshots__/destination-accessor.spec.ts.snap, packages/core/test/scp-cf/__snapshots__/destination.spec.ts.snap, packages/core/test/scp-cf/__snapshots__/env-destination-accessor.spec.ts.snap, packages/core/test/scp-cf/destination-accessor.spec.ts, packages/core/test/scp-cf/destination.spec.ts, packages/core/test/scp-cf/env-destination-accessor.spec.ts, packages/core/test/test-util/request-mocker.ts
This PR enables validation of the destinations env variable when set. A warning will be logged if destinations in the env variable do not contain a `name` or `url`.
=> chore: Validate destinations when reading from env variables

package-lock.json, packages/core/src/scp-cf/destination-service-types.ts, packages/core/src/scp-cf/destination-service.ts, packages/core/src/scp-cf/destination.ts, packages/core/test/scp-cf/__snapshots__/destination.spec.ts.snap, packages/core/test/scp-cf/destination.spec.ts, packages/core/test/test-util/example-destination-service-responses.ts
We recently introduced validation of configurations from env vars and the destination service (https://github.com/SAP/cloud-sdk/pull/44). As we currently parse all given destinations this will lead to errors, if there are destinations without 'URL'. This is the case for RFC type destinations, for example. This PR fixes that behavior and skips parsing of non HTTP destinations.
=> fix: Ignore destinations other than ‘HTTP’ for validation

packages/generator/src/batch/function.ts, packages/generator/src/complex-type/builder-function.ts, packages/generator/src/complex-type/interface.ts, packages/generator/src/entity/class.ts, packages/generator/src/entity/namespace.ts, packages/generator/src/function-import/parameters-interface.ts, packages/generator/src/request-builder/class.ts, packages/generator/src/typedoc.ts, packages/generator/test/complex-type/builder-function.spec.ts, packages/generator/test/complex-type/interface.spec.ts, packages/generator/test/function-import/parameters-interface.spec.ts, packages/generator/test/vdm-typedoc-generator.spec.ts
Due to the changed linting also the generated docs of the entities are changed. In the past the doc was created not in block form but the linter took accidentally care.
In this PR, empty lines are added so that the entities keep their nice block style as before.
In order to test, please run `npm run generate:tes-sources` and see if no changes are induced. I tried it, but you never know.
=> Fix: Adjust Generated Docs

docs/api/index.md, docs/api/latest.html, generate-docs.js, package-lock.json, package.json
This PR adds two things to the docs provided by the github pages:
- The index.html in `docs/api`  contains now the version sorted by latest on top
- There is a `latest.html` which redirects to the latest doc
It also changes the way the index is created. Instead of relying on the old file it considers all folders in the `docs/api` as a version so there is no risk of having multiple times the same line or a link to a non existing entry.
Testing is a bit difficult. What I did was adding a higher version in the `lerna.json` and then executed `npm run doc`. A new version appeared in the docs, index.html and the latest.html was adjusted. I then uploaded it to a private repo and it was working to. The redirect in the test was to the productive repo but I think this is ok.
=> chore: Improve the Docs overview Page

package-lock.json, test-packages/integration-tests/jest.config.js, test-packages/integration-tests/package.json, test-packages/integration-tests/test/proxy-skipped.spec.ts, test-packages/integration-tests/test/proxy.spec.ts
I added a proxy test that does not require any java runtime. Unfortunately I was not able to get this running for https, but I decided that this is already something worth merging.
=> chore: Re-enable proxy test

packages/generator/src/service/package-json.ts
Currently the versions the generated packages diverge from the versions of core. This can cause problems in the VDM.
=> chore: Update dev dependency versions of generated odata clients

.github/workflows/build.yml
There should be a different pipeline for docs
Current build pipeline is not applicable for `gh-pages` and `documentation` branches
=> Remove documentation & gh-page branch from build

README.md
Serving the documentation with Docker works for me (Windows, w/o Python/Node)
=> [documentation] Add Docker alternative

package-lock.json
Update the `package-lock.json` to allow for installation on a mac.
When running `npm ci` or even `npm install` fails on mac (at least for me).
After throwing away the `node_modules` as well as the `package-lock.json` I ran `npm install` which generated the adjusted `package-lock.json`.
This now works out of the box with the `npm ci` command.
Can some Linux (@artemkovalyov) and Windows users verify whether this also works for them?
=> [Docs] Adjusted package-lock.json to work on mac

packages/core/package-lock.json, packages/core/package.json
moment version 2.25.0 is breaks in frontends. Currently, there is no fix, therefore I restricted the version to ~2.24.0.
https://github.com/moment/moment/issues/5484
=> fix: Downgrade moment for frontend applications

README.md, packages/core/README.md, packages/generator/README.md, packages/test-util/README.md, packages/util/README.md
The api doc link in this page:https://www.npmjs.com/package/@sap-cloud-sdk/core is broken after switching to new doc portal.
We have to fix it.
=> chore: use new api doc link for the npm readme

.github/workflows/build.yml, .github/workflows/release.yml
Addressing comments to the previous pipeline setup for docs:
- Split into 2 files
- Rename `checks` to `build`
- Hydrate everything needless
- Improve naming for irrelevant things
- Reflect similar structure to master
- Permission is still managed via key
- Tested locally on my fork and proven to work
=> Split commit into 2 files, improve naming, fix typos

CHANGELOG.md, packages/generator/src/generator-cli.ts, packages/generator/src/generator.ts
Currently the VDM generation can take very long and the user does not see what is happening.
I added more log statements and also emitted each file separately compared to the whole project directory which seems to be also more performant. 
In order to improve the value we should also fix this issue in the CLI so that our logs are also shown when executed via the CLI: SAP/cloud-sdk-cli#55.
=> Fix: Improve logging on edmx generation and file creation

packages/generator/src/parser/service-parser.ts, packages/generator/src/parser/swagger-parser.ts
Currently the S4 VDM cannot be built, because some of the swagger files were replaced with openapi files. This change should hot fix our generator to be still compatible for both cases.
=> fix: Make swagger parsing compatible with openapi definitions

packages/generator/src/parser/swagger-parser.ts
Yesterday we merged a fix for the openapi update in the S4 VDMs. As there were minor concerns about the fix, here is a slight improvement, that might address the underlying concerns.
=> chore: Improve openapi fix

docs/java/features/odata/use-vdm.md
Small stylistic improvement: If an OData protocol version is selected it will be selected for all sections of the document. For reference please find the [documentation](https://v2.docusaurus.io/docs/markdown-features#syncing-tab-choices) on that feature.
This document is the only instance of the code base where this applies. For the [documentation on the generator](https://sap.github.io/cloud-sdk/docs/java/features/odata/java-generate-odata-vmd-v2-v4) this is already done in this PR: #132
=> Synchronise Tab Choices in OData Usage Documentation 

.github/workflows/build.yml
Reverts SAP/cloud-sdk#104
It seems that the force publishing makes the canary release failing.
=> Revert "Force publishing all packages when releasing a canary version"

scripts/generate-docs.js
@marikaner, for some reason you required to keep versions.json for the release purposes. This update to the docs generation script will full fill this requirement.
Don't see anything bad in having them both.
=> Create versions.json together with versions.js

.github/workflows/api-docs.yml, .github/workflows/build.yml
The pipeline was tested manually. What it does:
- triggered only on changes in the `docs` folder
- checks out master
- clones `documentation` branch into a separate folder
- syncs API docs inside of the container
- pushes to `documentation` branch which in turn triggers the release pipeline on it.
I manually tested it end to end
I also added the snippet below to `build.yml` to avoid running full builds on every docs change. 
```
paths-ignore:
- 'docs/**'
```
API docs should be now fully automated whenever anything new is added there which should make releasing less of a burden.
=> Pipeline to handle API reference update to documentation branch

packages/core/src/scp-cf/destination-accessor.ts
Spelling correction: 'Sucessful' -> 'Successful'
Correction of spelling of 'sucessful'.
'Successful' appears with the correct spelling in messages.
`please review`
=> fix: Corrected spelling of 'sucessful' in messages

CHANGELOG.md, packages/generator/src/complex-type/imports.ts, packages/generator/test/complex-type/imports.spec.ts, test-resources/service-specs/API_TEST_SRV/API_TEST_SRV.edmx
When a complex type is generated, the import statement should contain `FieldType` without any dependencies, because the `build()` function as shown below contains it.
```
export namespace RuleFieldMappingBeanList {
export function build(json: { [keys: string]: FieldType }): RuleFieldMappingBeanList {
return createComplexType(json, {
ruleFieldMappings: (ruleFieldMappings: RuleFieldMappingBean) => ({ ruleFieldMappings: RuleFieldMappingBean.build(ruleFieldMappings) })
});
}
}
```
* Use indicative and present tense. For example, write "Provide function …
=> fix: complex type import should contain FieldType

.github/workflows/build.yml
The force publish does not work if the same version id is used.
Now the git commit id is used as part of the alpha version.
=> chore: Replace lerna publish --canary with a workaround

.github/workflows/api-docs.yml
When creating a tag, a new release process is started by calling the script: `npx lerna version minor(or patch) --force-publish -y`.
This command actually also commit to master for some version updates.
As a result, both of the actions below trigger the GitHub action with the same git commit id:
- pushing a tag
- commit to master
One of them is duplicate so I would like to disable it.
=> chore: Remove duplicate doc update

.github/workflows/build.yml
Fix pipeline to only create one release
=> chore: Skip canary release on tag

scripts/generate-docs.js
To improve tracking and get insights on how heavily our API docs are used.
I tested locally docs generation with tracking inserted.
=> Inject tracking to API documentation for JS

CHANGELOG.md, packages/core/package-lock.json, packages/core/package.json, packages/core/src/util/jwt.ts, packages/core/test/test-util/environment-mocks.ts, packages/core/test/test-util/mocked-access-tokens.ts, packages/core/test/util/jwt.spec.ts
In the JWT verification method provided by the SDK we used the value `jku` of the JWT header without additional checks. This is not correct. To avoid manipulations the domains of the provided value and the `uaadomain` of the XSUAA credentials need to match.
This PR fixes this vulnerability. The PR where the problem came in was:
https://github.com/SAP/cloud-sdk/pull/100 merged 29th of March.
So if I see it correctly the versions:
- v1.21.1
- v1.21.0
- v1.20.1
- v1.20.0
- v1.19.0
are effected and should be marked as vulnerable so that npm audit give a error.
* Describe when or where this is …
=> Fix: Validate that domains match

packages/util/package-lock.json, packages/util/package.json
`lodash` has a vulnerability that the refuse to solve causing security checks of our customers to fail. `lodash` comes into our dependency tree transitively through `winston`:
`winston > async > lodash`. The `async` library has already released a new version (3 and onwards) where they got rid of `lodash`. `winston` is already referencing `async` v3 on their master, but they did not release a new version yet (there is an issue for that https://github.com/winstonjs/winston/issues/1812).  As we cannot tell how long this will take, maybe we should just update that version manually.
I modified the package-lock.json and added a newer version as a direct dependency. I am aware that this is not a clean way to do this, but it should close https://github.com/SAP/cloud-sdk/issues/135.
We should keep …
=> fix: Manually update version of vulnerable dependency

packages/core/src/odata/common/entity-deserializer.ts, packages/core/src/odata/v2/entity-deserializer.ts, packages/core/src/odata/v2/extract-odata-etag.ts, packages/core/src/odata/v2/index.ts, packages/core/src/odata/v4/entity-deserializer.ts, packages/core/src/odata/v4/extract-odata-etag.ts, packages/core/src/odata/v4/index.ts, packages/core/test/request-builder/get-by-key-request-builder-v4.spec.ts
The Etag information from the payload has different format in the OData V4 (`json.@odata.etag`) compared to V2(`json.__metadata.etag`).
Since the key of the header used is the same, the write operations are not affected.
=> feat: V4 etag handling

packages/util/package-lock.json, packages/util/package.json
As we have seen in the past, lodash is broken from a security perspective. The winston update fixes that.
Unfortunately in v3.3.1 of winston the maintainer added a git dependency that is causing pipelines of customers to fail.
~~This locks the winston version to the one healthy version 3.3.0.~~ Locking is not necessary anymore since v3.3.2.
Closes https://github.com/SAP/cloud-sdk/issues/206
=> chore: Update winston

test-packages/test-services/package.json, test-packages/test-services/tsconfig.json
The ts files are compiled for verifying whether they have compilation errors.
We have to disable them, since pipeline detects some changes after that then results in a canary release error.
=> chore: disable compile in test-services package

packages/core/src/odata/common/time.ts, packages/core/src/odata/v4/payload-value-converter.ts, packages/core/test/payload-value-converter-v4.spec.ts, packages/core/test/uri-value-converter-v4.spec.ts
Reduce number of generated types and represent fractional seconds as number instead of string. This comes with the tradeoff, that trailing zeros in fractions can get lost, but as discussed, we treat this as a corner case for now.
=> feat: Remove notion of fractional seconds

CHANGELOG.md, packages/core/src/odata/common/payload-value-converter.ts, packages/core/test/odata/payload-value-converter.spec.ts
we found a mistake in the code that for the conversion from the TS representation to edmx also the parseNumber method was used. This is not correct since the values 'INF','-INF' and 'NaN' are casted to Number.POSITIVE_INFINITY etc. So one needs a different conversion method to bring the number values back to the 'INF','-INF' and 'Nan' value. This fix provides this fix.
=> Fix: Conversion number TS to edm formats

CHANGELOG.md, packages/core/src/odata/common/request/odata-request.ts, packages/core/test/request-builder/odata-request.spec.ts
Currently, there is a default etag in the header: `if-match: false`, which breaks e.g., get all request (returns 409) if the OData Service checks this key.
As default behaviour, the key should not be set in the header.
=> fix: there should not be a if-match key in the header as default

CHANGELOG.md, packages/generator/src/parser/common/edmx-to-vdm.ts, test-resources/service-specs/v4/API_TEST_SRV/API_TEST_SRV.edmx
Currently we do not yet support enums which breaks the generation of v4 services. This is a hotfix that avoids generating properties that are enum types. Closes #222.
=> fix: Ignore enum properties in complex types

.github/workflows/build.yml
This PR introduces cache for npm ci to avoid unnecessary downloading.
All files under the folder `~/.npm`.
- `package-lock`s
- os (macos/ubuntu)
- node version
- without cache: check `npm ci` step on macos + node 12 [here](https://github.com/SAP/cloud-sdk/runs/872851856?check_suite_focus=true), which took 8+ min
- with cache: check `npm ci` steps [here](https://github.com/SAP/cloud-sdk/runs/872905490?check_suite_focus=true), which never consume 2+ min.
If you randomly check a [pipeline](https://github.com/SAP/cloud-sdk/runs/849821360?check_suite_focus=true) that takes 10 min, usually there is an `npm ci` that takes 3 or 4 min or even more like 8 min. This is the bottle neck, since they are running in parallel, only the slowest job is considered. The cache improves the bottle neck, because …
=> chore: Use cache for dependencies

.npmrc, .yarnrc
The https://registry.yarnpkg.com seems to be flaky: https://github.com/sourcegraph/sourcegraph/pull/926/.
Hence we use the npm repo with yarn.
=> Fix: use npm repo with yarn

packages/core/src/odata/common/batch-response.ts, packages/core/src/odata/v2/odata-batch-request-builder.ts, packages/core/src/odata/v2/request-builder/create-request-builder.ts, packages/core/src/odata/v2/request-builder/get-all-request-builder.ts, packages/core/src/odata/v2/request-builder/get-by-key-request-builder.ts, packages/core/src/odata/v2/request-builder/response-data-accessor.ts, packages/core/src/odata/v2/request-builder/response-transformers.ts, packages/core/src/odata/v4/odata-batch-request-builder.ts, packages/core/src/odata/v4/request-builder/create-request-builder.ts, packages/core/src/odata/v4/request-builder/get-all-request-builder.ts, packages/core/src/odata/v4/request-builder/get-by-key-request-builder.ts, packages/core/src/odata/v4/request-builder/response-data-accessor.ts, packages/core/src/odata/v4/request-builder/response-transformers.ts, packages/core/test/odata/v2/response-data-accessor.spec.ts, packages/core/test/odata/v4/response-data-accessor.spec.ts
Use centralized accessors for OData responses, that are different for v2/v4.
=> Fix: Use correct response accessors

CHANGELOG.md, packages/generator/src/generator-options.ts
As in the title + I changed the default of the option in the generator.
=> fix: Deprecate .npmrc generation

docs/js/features/connectivity/destination.md, docs/js/features/connectivity/proxy.md, docs/js/features/odata/use-generated-client.md
I noticed that our pages for JavaScript are not visited as often. Maybe this fixes a small part of the reason.
=> Spell out JS/TS

.github/workflows/build.yml, .yarnrc, test-packages/e2e-tests/package.json, yarn.lock
Although the yarnrc has the proper config for the registry, but the lock is still using the yarn registry, which needs to be re-generated.
=> fix: use npm registry by updating yarn lock

docs/java/features/connectivity/destinations.md
This PR adds a small note on how the SDK fetches destinations from the destination service in a multi tenant scenario.
=> [Java] Add Note on Multi Tenancy to destination documentation

CHANGELOG.md, packages/generator/src/generator.ts
In the VDM we found an error for the `API_PRODUCT_AVAILY_INFO_BASIC` service. This service does not have any entities. Only function imports and some types. In this case the `Batch.ts` files were erroneous. I just skipped the generation of the batch file in this case. 
Should we add an extra test for this? This would mean a edmx without an entity?
~~- [ ] If applicable: Properly documented …
=> Fix:  Generator error for services without Entities

docs/java/features/odata/redirect-typed-client.md, docs/js/features/odata/redirect-generate-typed-odata-v2-and-v4-client-for-javascript-and-typescript.md, docs/js/features/odata/redirect-generator-js-sdk.md, docs/js/features/odata/redirect-use-typed-odata-client-for-javascript-and-typescript.md, docs/js/features/odata/redirect-use-typed-odata-client-for-js.md, docs/js/features/odata/redirect-use-typed-odata-v2-client-for-javascript-and-typescript.md, docs/js/features/odata/redirect-use-typed-odata-v4-client-for-javascript-and-typescript.md, docusaurus.config.js, sidebars.js
As in the title - I made the redirect more verbose, I don't see a reason why it wouldn't work correctly now...
=> docs: More verbose, but redirects should work now

LICENSES/Apache-2.0.txt
we were a bit unsure which licence to put for the documentation. The OSPO clarfied that for the documentation the same licence can be used as for the code which of OS is the apache 2.0 licence. 
In principle we have this licence already on master. But since the documentation branch is so different I added the licence once more also to this branch. This can not hurt and we are on the save side.
=> Add Licence File

CHANGELOG.md, packages/generator/src/generator-utils.ts, packages/generator/src/generator.ts, packages/generator/src/service/index-file.ts
We stopped generating the `Batch.ts` when there is no entity. In this case, the index file should not export the batch.
I manually tested the generated folder for compilation checks, which should be done automatically soon.
=> fix: generated index file should not export batch when no batch can be found

docs/js/features/odata/odata-v4-client.mdx
I made a mistake to commit to the `document` branch directly, which tried to use the `useBaseUrl `.
Switched to the full url.
Here is an related [issue](https://github.com/facebook/docusaurus/issues/3303), saying there can be false positive and how to disable it via config.
However, the config is about to change `navbar/footer` items, which is not applicable in our case.
=> fix: use full url for linking to api doc

test-packages/e2e-tests/test/request-builder.spec.ts
The v4 version of the `asChildOf` does the same thing as the v2. Therefore, as expected, the implementation is there and can be moved to abstract request builder later. The idea of this ticket is then to verify against a real v4 system (CAP). 
=> chore: as child of

docs/dzen/getting-started.mdx, docs/java/features/odata/generate-client.mdx, docs/java/features/resilience/resilience.mdx, docs/java/getting-started.mdx, docs/java/guides/dependencies.mdx, docs/java/troubleshooting.mdx, docs/js/features/connectivity/destination.mdx, docs/js/features/connectivity/on-premise.mdx, docs/js/features/connectivity/proxy.mdx, docs/js/features/odata/generic-http-client.mdx, docs/js/getting-started.mdx, docs/js/guides/bas-external-system.mdx
I renamed the .md files consistently to .mdx but this broke the build. This PR tries to fix it.
=> [Fix] Renaming to .mdx broke the Documentation Build

docs/java/features/bapi-and-rfc/overview.mdx
Enhance the existing BAPI documentation about the Web Socket RFC client communication provided with JCo 3.1.2.
=> Add chapter about websocket rfc client

test-packages/e2e-tests/test/request-builder.spec.ts
I picked the documentation issue for the `asChildOf` functionality. When I was going over the code samples I realized, that we do not have an E2E test for this functionality. So I added a test against the CAP service. Works just fine.
=> [Chore] Add E2E test for asChildOf

package.json, yarn.lock
we have a security warning due to `bl@1.2.2` which is fixed in version `1.2.3` of `bl`. This comes in via the `dtslint` type test package, so it does not affect any productive situation. But it good to not have this yellow banner every time I open the SDK.
Yarn is very convinient:
- `yarn why bl` tells you why the dependency is installed
- with an entry in the resolution entry `libHavingItAsDependency/libToReplaceVersion: newVersion`  you can overrule the version used.
=> [Chore] Remove BL security warning

CHANGELOG.md, packages/core/src/odata/v4/uri-conversion/get-expand.ts, packages/core/test/request-builder/request/v4/get-expand.spec.ts
We did not consider the `orderBy` in expanded subqieries.
~~- [ ] If applicable: Properly documented (JSDoc of public API)~~
~~- [ ] If applicable: Check if `node run doc` still works.~~
=> [Fix] add orderBy in expanded subqueries

CHANGELOG.md, packages/core/src/odata/common/entity-deserializer.ts, packages/core/src/odata/v2/entity-deserializer.ts, packages/core/src/odata/v2/extract-data-from-one-to-many-link.ts, packages/core/src/odata/v2/request-builder/response-data-accessor.ts, packages/core/src/odata/v4/entity-deserializer.ts, packages/core/src/odata/v4/extract-data-from-one-to-many-link.ts, packages/core/src/odata/v4/request-builder/response-data-accessor.ts
This is what I meant with "use the response accessor". I think we should definitely pass the response accessor to the deserializer not some specific functions, but this should happen on a separate ticket. This would only be the first step to have the "data accessing" functionality in one place. I created a separate PR for your branch, @FrankEssenberger, to make it easier for you to see the changes (that I reverted to before my comments and then used the accessor).
=> Response accessor

CHANGELOG.md, packages/core/src/odata/common/entity-deserializer.ts, packages/core/src/odata/v2/entity-deserializer.ts, packages/core/src/odata/v2/extract-data-from-one-to-many-link.ts, packages/core/src/odata/v2/request-builder/response-data-accessor.ts, packages/core/src/odata/v4/entity-deserializer.ts, packages/core/src/odata/v4/extract-data-from-one-to-many-link.ts, packages/core/src/odata/v4/request-builder/response-data-accessor.ts, packages/core/test/odata/v2/entity-deserializer.spec.ts, packages/core/test/odata/v2/response-data-accessor.spec.ts, packages/core/test/odata/v4/response-data-accessor.spec.ts
In general for OData v2 an expanded nav property as the form `{results:[]} i.e. the navigation entities are wrapped in a results object. For C4C this seems to be not the case see here #508 
This PR makes the data extraction more flexible.
~~- [ ] If applicable: Check if `node run doc` still works.~~
=> [Fix] Response parsing of 1:N relations in C4C

packages/core/src/odata/v2/request-builder/create-request-builder.ts, packages/core/src/odata/v2/request-builder/update-request-builder.ts, packages/core/src/odata/v4/request-builder/create-request-builder.ts, packages/core/src/odata/v4/request-builder/update-request-builder.ts
The `prepare` function was introduced a long time ago. The name does not say what this function does, it has a side effect and in order to execute a request it had to be called before. I deprecated it and replaced its usage.
=> fix: Remove dangerous prepare method

packages/core/src/header-builder/authorization-header.ts, packages/core/src/odata/common/response-data-accessor.ts, packages/core/test/request-builder/header-builder/authorization-header.spec.ts
The warning message had some weird formatting. Also, I got this message, when I passed a destination directly. Those don't have a name so I got a message telling me that the "destination undefined" had auth headers.
In general I think we need to rethink how we go about headers. At the moment this warning also occurs when there are no custom headers set. I guess this is because the generic http client uses them. As this is only a warning, maybe this is low priority.
* Use indicative and present tense. For example, write "Provide function `name` that …
=> chore: Improve auth header warning

packages/core/src/odata/common/request-builder/request-builder-base.ts, packages/core/src/odata/common/request/odata-request.ts
Add an extra function that separates the destination and csrf headers from "basic" headers. Those are the only ones relevant for batch.
=> chore: Separate basic headers from other dest + csrf headers

.github/workflows/build.yml
canary release failed:
```
21s
1
Run yarn install --frozen-lockfile
4
yarn install v1.22.4
5
[1/4] Resolving packages...
6
[2/4] Fetching packages...
7
warning Pattern ["@definitelytyped/typescript-versions@latest"] is trying to unpack in the same destination "/home/runner/.cache/yarn/v6/npm-@definitelytyped-typescript-versions-0.0.48-9df9179100a90422acd9e4e973277aa36cf71e5a-integrity/node_modules/@definitelytyped/typescript-versions" as pattern ["@definitelytyped/typescript-versions@^0.0.48","@definitelytyped/typescript-versions@^0.0.48"]. This could result in non-deterministic behavior, skipping.
8
error https://npm.sap.com/@sap/cds-reflect/-/cds-reflect-2.12.2.tgz: Integrity check failed for "@sap/cds-reflect" (computed integrity doesn't match our records, got …
```
=> fix: canary release by applying cache

packages/core/src/odata/v2/entity-deserializer.ts, packages/core/src/odata/v2/entity-serializer.ts, packages/core/src/odata/v4/entity-deserializer.ts, packages/core/src/odata/v4/entity-serializer.ts
There was an error in a reference to [[EntitySerializerType]] which is an interface now an just called [[EntitySerializer]].
=> [Fix] In the TsDoc was a reference to a type

CHANGELOG.md, packages/generator/package.json
`execa` was declared as a dev dependency, but used in the productive code. This PR fixes that.
Reported in #559.
=> chore: Make execa a dependency not a dev dependency

CHANGELOG.md, packages/core/src/header-builder/csrf-token-header.ts
In e2e test vdm, batch failed with OP destination, the error was:
`The error response is undefined.\n    at /home/vcap/app/node_modules/@sap-cloud-sdk/core/src/header-builder/csrf-token-header.ts`
=> fix: the original error is shown when retrieving csrf token

CHANGELOG.md, packages/core/src/http-client/http-client.ts, packages/core/test/http-client/http-client.spec.ts
Custom header are supported when executing http request. Since it will be used instead of the ones fetched from the destination service, more warning messages should be helpful.
=> chore: add debug/warning msg when using custom header 

package.json, yarn.lock
Lock the agent lib to version 6.0.2 at least to be up to date with node.
=> chore: Lock agent base to version 6.0.2 at least

CHANGELOG.md, packages/core/src/scp-cf/client-credentials-token-cache.ts, packages/core/src/scp-cf/xsuaa-service-types.ts, packages/core/test/scp-cf/client-credentials-token-cache.spec.ts
Currently, the cache is never hit even with 2 get all requests within a second.
=> fix: client credential cache

test-packages/e2e-tests/test/request-builder.spec.ts
The request builder test was broken for me last week. Another change fixed it since then but this should make it less brittle in the future and also extend the scope of the test for better coverage.
Follow up/replacement of this PR: #668
=> chore: Add filter condition to request build e2e test

CHANGELOG.md, packages/core/src/odata-common/batch-response.ts, packages/core/src/odata-common/request-builder/batch/batch-response-deserializer.ts
In my batch v4 refactoring a while back, I think I made a wrong assumption on a type. If the type remains as is, users would have to always cast the result from `.as(BusinessPartner) as BusinessPartner` otherwise it can be either an error or a business partner. Instead as should only be called, when we know it is not an error. I described this behavior in https://github.com/SAP/cloud-sdk/pull/11.
=> fix: Fix batch read response type

packages/rest-generator/openapitools.json, packages/rest-generator/package.json, yarn.lock
The current "stable" version of the OpenAPI generator is broken. The beta version seems to work fine, I was able to transpile the results.
=> chore: Use beta version of the open api generator

.github/workflows/api-docs.yml
I updated the snippet that syncs the repos. This should do the work now. Please, take a look.
=> Fix api docs pipeline to work between two repos

packages/test-util/src/test-destination-mocker.spec.ts, packages/test-util/src/test-destination-provider.spec.ts
Just two files. However, I could move all the test-util files from the other packages in this one. I do not know if this makes sense. It would add some sort of coupling one would perhaps like to avoid.
On the other had it could make reuse easier.
=> chore: Move spec files for test-util package

package.json, packages/analytics/package.json, packages/core/package.json, packages/generator/package.json, packages/openapi-generator/package.json, packages/test-util/package.json, packages/util/package.json, test-packages/e2e-tests/package.json, test-packages/integration-tests/package.json, test-packages/type-tests/package.json
In the `package.json` the `repository` was still pointing to the `cloud-sdk` repo which is now the doc repo. And the `homepage` used the community url which I thought is also not that informative than our github pages.
=> chore: adjust the repo and homepage url

packages/openapi-generator/src/parser/document.ts, packages/openapi-generator/src/parser/operation.spec.ts, packages/openapi-generator/src/parser/operation.ts, packages/openapi-generator/src/parser/parameters.spec.ts, packages/openapi-generator/src/parser/parameters.ts, packages/openapi-generator/src/wrapper-files/__snapshots__/api-file.spec.ts.snap, packages/openapi-generator/src/wrapper-files/api-file.spec.ts, packages/openapi-generator/src/wrapper-files/api-file.ts, packages/util/src/array.spec.ts, packages/util/src/array.ts, test-packages/e2e-tests/test/openapi.spec.ts, test-packages/test-services/openapi/test-service/api.ts, test-packages/test-services/openapi/test-service/open-api.json, test-packages/test-services/openapi/test-service/openapi/api/default-api.ts, test-resources/openapi-service-specs/test-service.json, yarn.lock
Fixes the order of parameters. The parameters in the default api are - required params, optional params, depending on order in the spec file. The order in our api is - required path params, required body, required query params, optional path params, optional query params.
After I had already implemented that, I had an insightful conversation with @jjtang1985: We should probably have a parameter object instead of multiple parameters, because if this gets bigger the API gets quite ugly. That way the order wouldn't matter, we would have to only keep it to call the default api.
@FrankEssenberger @florian-richter - I left the reordering for now, but I will be happy to still improve this on this PR.
=> fix: Fix order of parameters

packages/core/src/openapi/openapi-request-builder.spec.ts, packages/core/src/openapi/openapi-request-builder.ts, packages/core/src/openapi/types.ts, test-packages/e2e-tests/test/openapi.spec.ts
Introduce `executeRaw` that returns an AxiosResponse and return the plain response value in `execute`. Also adds tests.
=> chore: Unwrap axios response

openapitools.json, packages/openapi-generator/src/generator.ts
Locks the cwd of the execution of the java openapi generator to the generator directory. Prevents creation of a new openapi-tools.json and thereby ensures usage of the version we specified.
=> chore: Remove openapi tools json

typedoc.json
To fix the error below when triggering a new release:
```
Error: Command failed: npx typedoc .
No lerna package found for /../cloud-sdk-js/knowledge-base/adr/0017-code-snippets.ts
```
=> fix: typedoc config

.github/workflows/bump.yml, knowledge-base/how-tos/release.md, package.json
There were multiple occurrences where we published files that we had lying around locally because the release was triggered manually from our workspaces. In order to never run into those issues again, I created this script. I tested it on a different repository.
=> chore: Add bump workflow

README.md
It was fully merged into project project "Piper".
=> Remove hint about cloud sdk pipeline

.github/workflows/build.yml
Add a new check for the api doc generation so we detect potential issues before merging to master.
=> chore: check api doc generation

CHANGELOG.md, packages/openapi-generator/tsconfig.json
The openapi cli fails with the error ``TypeError: Class constructor Command cannot be invoked without 'new'``, due to the incompatibility of ES5 and oclif (ES2017).
The internal generator e2e tests are added.
=> fix: openapi cli

CHANGELOG.md, packages/openapi-generator/src/document-converter.spec.ts, packages/openapi-generator/src/document-converter.ts, packages/openapi-generator/src/openapi-types.ts, packages/openapi-generator/src/parser/document.ts, packages/openapi-generator/src/parser/operation.spec.ts, packages/openapi-generator/src/parser/operation.ts, packages/openapi-generator/src/wrapper-files/api-file.spec.ts, packages/openapi-generator/src/wrapper-files/api-file.ts, packages/util/src/code-block.spec.ts, packages/util/src/code-block.ts, test-packages/test-services/openapi/test-service/api.ts, test-packages/test-services/openapi/test-service/open-api.json, test-packages/test-services/openapi/test-service/openapi/api/default-api.ts, test-resources/openapi-service-specs/test-service.json
This should allow us to generate for erroneous specifications as well.
=> fix: Allow duplicate and no operationIds

knowledge-base/adr/0015-date-time-handling.md
In the ADR `0015-date-time-handling.md`, we decided to make an interface so users could choose the date time lib and custom the (de)serialiser. 
The [PoC](https://github.com/SAP/cloud-sdk-js/pull/921) of such design was successful.
This PR reflects the status of the PoC in the aspects:
- new api design
- assumption
- scope
- how to get rid of moment
- next steps
=> chore: Moment poc ADR

scripts/generate-test-services.ts
- Fix the warning:
`UnhandledPromiseRejectionWarning: Error: Reading test service file 'openapi' failed: Error: EISDIR: illegal operation on a directory` by applying a filter `dirent.isFile()`.
- The script will fail in there future instead of having a warning.
=> chore: fix the unhandledRejection warning when generating test services

scripts/generate-test-services.ts
It was a mistake that this line was removed.
=> fix:generate-test-service

packages/generator/src/generator-utils.ts, packages/generator/src/generator.ts, packages/openapi-generator/src/generator-utils.ts, packages/openapi-generator/src/generator.ts, packages/util/package.json, packages/util/src/fs.ts
Having `execa` in utils breaks the frontend e2e tests. I was able to fix that to a certain degree, but this will also break for users who use the SDK in the frontend. In order to avoid that, I thought it might be nice, to for now just duplicate this one function and later on put this into a separate library as discussed.
Let me know if this makes sense for you.
=> chore: Move transpilation to generators

packages/generator/package.json, packages/generator/src/input-path-provider.spec.ts, packages/generator/src/input-path-provider.ts
This is a further improvement, because the old version actually fails in some cases (e. g. if swagger enhancement is enabled and there is a .xml, but no .json file, we currently return the original .xml filepath. Later on JSON.parse generation will fail).
=> fix: Improve swagger path generation to actually check for file paths

.github/workflows/build.yml
It happened 5+ times (on Feb.12th) that the GH Actions cost 20+ minute, because of the waiting time of the Mac OS containers.
I guess with more people working on it, it's harder to get the containers.
In this PR, I would like to minimise the usage of the Mac OS container and only keep using one.
I disabled the combination of Mac OS and node 10, since we still have two cases below:
- Mac OS and node 12
- ubuntu and node 10 
Let me know your opinion.
=> chore: Reduce the usage of Mac OS in the tests

.gitignore, packages/openapi-generator/openapitools.json
The jar file needs to be downloaded on the fly when necessary. The URL (maven central) for downloading the jar file is not configurable. This is the solution when downloading from external target URL is not allowed.
=> chore: commit openapi jar

CHANGELOG.md, packages/core/src/connectivity/scp-cf/connectivity-service.spec.ts, packages/core/src/connectivity/scp-cf/proxy-util.ts, packages/core/src/http-client/http-agent.spec.ts, packages/core/src/http-client/http-agent.ts, packages/core/test/test-util/environment-mocks.ts, test-packages/integration-tests/test/auth-flows/auth-flow-util.ts, test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts
I realized while working on BAS that client certificate authentication is not working when also proxies are used.
I adjusted our code that the proxy settings are also passed to the http-agent. Unfortunately also the proxy agent itself does not forward the presented certificates to the target system. So they stay on the proxy and you get a 401.
I checked by locally adjusting the node modules that this PR https://github.com/TooTallNate/node-https-proxy-agent/pull/111 fixes the issue, but the repo seems to be not very active. We can merge the code on our side but it will not work until we get an update on the node-https-proxy and this could take a while...
=> fix: Proxy and client cert authentication

packages/core/src/connectivity/scp-cf/authorization-header.ts, packages/core/src/connectivity/scp-cf/csrf-token-header.spec.ts, packages/core/src/connectivity/scp-cf/csrf-token-header.ts
Relates to #1037 and changes the logic that first the call is made against the URL with a `/` in the end.
=> fix: Fix Redirect issue in latest BAS on CF

.github/workflows/dependabot-autofix.yml
This should fix the authentication issue with the dependabot, it now provides the token as an environment variable.
=> chore: dependabot-github-action

.github/workflows/dependabot-autofix.yml
This PR tries to give dependabot workflows access to secrets.
=> fix: dependabot-workflow

packages/generator/src/edmx-parser/edmx-file-reader.spec.ts, packages/generator/src/edmx-parser/v2/edmx-parser.spec.ts, packages/generator/src/edmx-parser/v4/edmx-parser.spec.ts, packages/generator/src/generator-cli.spec.ts, packages/generator/src/generator.spec.ts, packages/generator/src/service-generator.spec.ts, packages/generator/src/swagger-parser/swagger-parser.spec.ts, packages/generator/test/test-util/generator.ts
In the sdk metadata PR I introduced a `index.ts` giving the location of the OData service specs. Using this file one can get rid of the hard coded file paths which makes the code more resilient to refactoring in the future. Also due to operating system differences in the file paths it is always better to use `resolve` to build paths for read methods.
=> chore: reduce hard coded paths

.github/workflows/api-docs.yml, .github/workflows/build.yml, .github/workflows/bump.yml, .github/workflows/release.yml, packages/cli/src/commands/add-approuter.ts
- `yarn install --frozen-lockfile` is now only run if changes to the `yarn.lock` were made
- we don't cache the `yarn` cache anymore, instead, we cache `node_modules` and our transpiled typescript (e.g. `**/dist`)
- if the `yarn.lock` didn't change, we only compile the packages that were changed, with `yarn lerna run compile --since origin/<branch>` (e.g. `origin/main`)
- update all standard actions to `@v2` from `@v1`
- Average 1min faster, because `yarn install` becomes redundant in most cases
- Especially faster when multiple build workflows are queued, 5x`yarn install` less/workflow results in a lot less resource usage
- The macOS environment is very flaky, which results in random test durations, this is apparently due to GitHub limitations
- `build once` (caching the entire repo …
=> improve pipeline

.github/workflows/build.yml, packages/cli/src/commands/add-approuter.ts
- Fixes the branch reference (previous one relied on `pull_request` event, which passes the pipeline in a pull request, but fails when pushing to main
- Change `== 'false'` to `!= 'true'`, `steps.outputs.cache.cache-hit` doesn't return `false` when no cache is hit, instead it returns `null`, already reported [bug](https://github.com/actions/cache/issues/533)
=> fix: pipeline-improvement

.github/workflows/build.yml
The compilation fo the `main` branch was skipped withe the option `--since`. Without the compilation, packages like `type-tests`/`integration-tests` use the old version (cache) of the `core`, making the failing pipeline.
=> Fix: force compilation

CHANGELOG.md, packages/core/src/openapi/openapi-request-builder.spec.ts, packages/core/src/openapi/openapi-request-builder.ts, test-packages/e2e-tests/openapi.js, test-resources/openapi-service-specs/test-service.json
Fetches a CSRF token before making the modifying request.
=> feat: Use CSRF token in OpenAPI request builder by default

CHANGELOG.md, packages/openapi-generator/src/parser/schema.spec.ts, packages/openapi-generator/src/parser/schema.ts
Use string as a default for enums.
=> fix: Use string as default for enums

CHANGELOG.md, packages/core/src/odata-common/request-builder/batch/__snapshots__/batch-request-serializer.spec.ts.snap, packages/core/src/odata-common/request-builder/batch/batch-request-serializer.spec.ts, packages/core/src/odata-common/request-builder/batch/batch-request-serializer.ts
Fix double encoding of filter parameters in batch requests.
=> fix: Double encoding of filter parameters in batch

.github/workflows/build.yml
- Removes `dist` from the cache in the pipeline
- Transpiles entire code instead of difference to main
If a previous `build` workflow had the same `yarn.lock` and `os`, its `dist` folder got used in the following `build` workflow, which leads to issues if the code had any bugs and worked on different packages than the following `build` workflow (e.g. triggered by a different PR), since only the difference to `origin/main` got transpiled, which can (and did!) lead to an unwanted cache overlap.
=> fix: dist cache overlap

packages/analytics/README.md, packages/cli/README.md, packages/core/README.md, packages/eslint-config/README.md, packages/generator/README.md, packages/openapi-generator/README.md, packages/openapi-generator/package.json, packages/openapi-generator/src/cli/index.ts, packages/test-util/README.md, packages/util/README.md, scripts/replace-common-readme.ts
This fixes the missing usage section in the readme of the openapi generator. The issue seems to have been caused by how the version was read.
=> fix: Fix OpenAPI readme

CHANGELOG.md, packages/core/src/odata-common/request-builder/request-builder-base.ts, packages/core/src/odata-common/request/odata-request-config.ts, packages/core/src/odata-common/request/odata-request.ts, packages/core/src/odata-v2/request-builder/create-request-builder.spec.ts, packages/core/src/openapi/openapi-request-builder.spec.ts, packages/core/src/openapi/openapi-request-builder.ts
Related to: https://github.com/SAP/cloud-sdk-js/issues/1185 and https://github.com/SAP/cloud-sdk-js/issues/606
=> feat: support disabling csrf token request

packages/openapi-generator/README.md, packages/openapi-generator/src/cli/index.ts
I noticed some unusual expression and/or typos. This fixes those.
=> chore: Improve the generator option descriptions

.github/workflows/build.yml
As discussed in retro today we remove the macos tests because they did not add much value but increased the test run time.
=> chore: remove macos tests

CHANGELOG.md, packages/core/src/odata-common/filter/boolean-filter-function.ts, packages/core/src/odata-common/filter/filter.ts, packages/core/src/odata-common/filter/filterable.ts, packages/core/src/odata-common/filter/index.ts, packages/core/src/odata-common/filter/unary-filter.ts, packages/core/src/odata-common/uri-conversion/get-filter.ts, packages/core/src/odata-v2/uri-conversion/odata-uri.spec.ts
=> feat: support unary operator not when building filters and improve boolean filter functions.

packages/openapi-generator/src/file-serializer/api-file.spec.ts, packages/openapi-generator/src/file-serializer/index-file.spec.ts, packages/openapi-generator/src/file-serializer/index-file.ts, packages/openapi-generator/src/file-serializer/operation.spec.ts, packages/openapi-generator/src/file-serializer/schema-file.spec.ts, packages/openapi-generator/src/file-serializer/schema-file.ts, packages/openapi-generator/src/file-serializer/schema.spec.ts, packages/openapi-generator/src/generator.ts, packages/openapi-generator/src/openapi-types.ts, packages/openapi-generator/src/parser/api.ts, packages/openapi-generator/src/parser/document.spec.ts, packages/openapi-generator/src/parser/document.ts, packages/openapi-generator/src/parser/media-type.ts, packages/openapi-generator/src/parser/operation.ts, packages/openapi-generator/src/parser/parsing-info.ts, packages/openapi-generator/src/parser/request-body.spec.ts, packages/openapi-generator/src/parser/request-body.ts, packages/openapi-generator/src/parser/responses.spec.ts, packages/openapi-generator/src/parser/responses.ts, packages/openapi-generator/src/parser/schema.spec.ts, packages/openapi-generator/src/parser/schema.ts, packages/openapi-generator/src/parser/unique-naming.spec.ts, packages/openapi-generator/src/parser/unique-naming.ts, packages/openapi-generator/src/schema-util.spec.ts, packages/openapi-generator/src/schema-util.ts, test-packages/test-services/openapi/swagger-yaml-service/schema/index.d.ts.map, test-packages/test-services/openapi/swagger-yaml-service/schema/index.js.map, test-packages/test-services/openapi/test-service/schema/index.d.ts.map, test-packages/test-services/openapi/test-service/schema/index.js.map
This fixes naming and import conflicts in schemas, e.g. for the `index` file.
There is a single source of truth for filenames now and they are not derived from the schema name anymore.
=> Fix schema name conflicts

packages/openapi-generator/src/parser/api.ts, packages/openapi-generator/src/parser/operation.spec.ts, packages/openapi-generator/src/parser/operation.ts, packages/openapi-generator/src/parser/refs.ts, packages/openapi-generator/src/parser/unique-naming.spec.ts, packages/openapi-generator/src/parser/unique-naming.ts
Simplify unique naming functions by a lot. Left-over suggestions from @FrankEssenberger.
=> chore: Refactor unique naming functions

packages/core/test/test-util/test-services/openapi/test-service/entity-api.ts, packages/openapi-generator/src/parser/schema.spec.ts, packages/openapi-generator/src/parser/schema.ts, test-packages/e2e-tests/test/openapi.spec.ts, test-packages/test-services/openapi/test-service/entity-api.d.ts, test-packages/test-services/openapi/test-service/entity-api.ts, test-resources/openapi-service-specs/test-service.json
Escape `'` in enum strings. Since the outer `'` are already added in the parsing, I added the escaping also directly there.
=> escape ' for enum strings

.github/workflows/build.yml
Today is the last day of the node 10 lifecycle.
https://nodejs.org/en/about/releases/
=> chore: disable node 10

packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap, packages/generator/src/sdk-metadata/sdk-metadata.spec.ts, packages/openapi-generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap, packages/openapi-generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap, packages/openapi-generator/src/sdk-metadata/generation-and-usage.spec.ts, packages/openapi-generator/src/sdk-metadata/sdk-metadata.spec.ts
This test fails with other versions than 1.41.1
=> chore: Fix metadata test to be sdk version independent

packages/generator/src/service/package-json.ts, packages/openapi-generator/src/file-serializer/__snapshots__/package-json.spec.ts.snap, packages/openapi-generator/src/file-serializer/package-json.ts, test-packages/test-services/openapi/no-schema-service/package.json, test-packages/test-services/openapi/swagger-yaml-service/package.json, test-packages/test-services/openapi/test-service/package.json
The `typedoc` version of the generated client is up-to-date.
=> chore: update typedoc in the client

CHANGELOG.md, packages/core/src/odata-common/request-builder/request-builder-base.ts, packages/core/src/odata-common/request/odata-request-config.ts, packages/core/src/odata-common/request/odata-request.spec.ts, packages/core/src/odata-common/request/odata-request.ts, packages/core/src/odata-v2/request-builder/get-all-request-builder.spec.ts, packages/core/src/odata-v2/request-builder/get-by-key-request-builder.spec.ts, packages/core/test/test-util/test-data.ts, test-packages/e2e-tests/test/TripPin/request-builder.spec.ts, test-packages/e2e-tests/test/request-builder.spec.ts
The `appendPath` is implemented as a workaround for almost all unsupported odata functionalities.
Typically, it can help queryi navigation properties (`GET` `/TestEntity(key)/to_MultiLink`).
Unfortunately, however, this function is too powerful, so the deserialisation cannot work as the return type is not clear.
I disabled the `execute` function when `appendPath` is called, and the users should use `executeRaw` instead.
=> feat: support appending path to generated url for all request builders

.github/workflows/bump.yml
For the last 10 releases, we have 8 minor releases + 2 patch releases. So minor matches to the most of the cases.
=> chore: use minor as default release parameter instead of patch

packages/core/package.json, packages/core/src/connectivity/scp-cf/resilience-options.ts
The generator tests failed with error:
```
05:46:55      [2021-05-26T03:46:07.784Z] [31mERROR[39m    (generator-cli): ErrorWithCause: Generation of services failed.
05:46:55  
05:46:55        at new ErrorWithCause (node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:32:16)
05:46:55        at node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js:33:18
05:46:55        Caused by:
05:46:55        Error: Compilation Errors:
05:46:55        /home/jenkins/agent/workspace/js-sdk-e2e-test-generator/e2e-test-generator/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/resilience-options.d.ts:1:27 - error TS7016: [object Object]
05:46:55        at Object.<anonymous> (node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:69:31)
05:46:55        at step …
```
=> Fix: opossum compilation error

CHANGELOG.md, packages/core/src/http-client/csrf-token-header.spec.ts, packages/core/src/http-client/csrf-token-header.ts, packages/core/src/http-client/index.ts
Always overwrite the content length header to be 0, which is the correct length of a HEAD request.
Related to #1320
=> fix: Fix CSRF fetch content length header

scripts/generate-docs.ts
Causes the documentation check to fail if any step of the generation fails.
=> chore: Wrap catch around whole doc generation

CHANGELOG.md, packages/openapi-generator/src/parser/operation.spec.ts, packages/openapi-generator/src/parser/operation.ts
There are two failing generation due to the special paths:
- /somePath/{param1}:{param2}, where `:` is used as delimiter between multiple parameters
- /somePath/value?param={date}-{time}, where `?` and query parameters are shown in the path
I added a validation step and improved the error message.
=> fix: error messages of invalid path patterns

CHANGELOG.md, packages/openapi-generator/src/generator.spec.ts, packages/openapi-generator/src/options/options-per-service.spec.ts, packages/openapi-generator/src/options/options-per-service.ts, packages/openapi-generator/src/parser/refs.spec.ts, packages/openapi-generator/src/parser/refs.ts, packages/openapi-generator/src/parser/schema-naming.spec.ts, packages/openapi-generator/src/parser/schema-naming.ts, packages/openapi-generator/src/parser/unique-naming.ts, test-packages/type-tests/test/v2/filter.spec.ts
This PR includes some minor refactoring of descriptions and error messages.
The main purpose is to fix the uniqueness check for directory names. Before, we checked the `serviceName` in `optionsPerService` for uniqueness. The purpose of this field is solely to have a human readable text in the readme and API docs. It is ok if this is duplicate. It is not for directory names, though.
=> fix: Fix uniqueness check on directory names

packages/generator-common/internal.js, packages/generator-common/package.json
For the oData and openApi generators we were already exporting the metadata under the non root to be used by us internally. We did not do this for the generator-common part which was introduced later.
=> chore: export sdk-metatdata in generator common

CHANGELOG.md, packages/core/src/connectivity/scp-cf/destination/destination-service.ts, packages/core/src/http-client/http-client.spec.ts, packages/openapi-generator/src/parser/schema-naming.ts
closes #1384 
@johenning found an error in the proxy handling. We included the default agents in the passed request config. This config beats the one from the destination, which is intended to have a way to overwrite things.
However, if the destination had a valid internet proxy config this would would overwrite the config from the destination and leads the error @johenning observed.
Note that es always add the [axios default config](https://github.com/SAP/cloud-sdk-js/blob/40c006573602c6813d51714073f6ee6055006b4c/packages/core/src/http-client/http-client.ts#L205) with the agents which gets overwritten by everything else. So there is no need to add this in the config at all.
=> fix: Proxy config not considered for destination service calls

CHANGELOG.md, packages/core/src/odata-common/uri-conversion/get-filter.ts, packages/core/src/odata-v4/uri-conversion/odata-uri.spec.ts, packages/core/test/test-util/filter-factory.ts
Last time, the type error (compile time) was fixed, but the runtime error still exists: `Could not construct query parameters from filter. Filter is not valid`, as mentioned in the [issue](https://github.com/SAP/cloud-sdk-js/issues/1338).
This PR will fix the runtime error.
=> Fix: lambda expression with or operand

CHANGELOG.md, packages/core/src/connectivity/scp-cf/authorization-header.ts, packages/core/src/connectivity/scp-cf/client-credentials-token.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts, packages/core/src/connectivity/scp-cf/destination/destination-service-types.ts, packages/core/test/test-util/example-destination-service-responses.ts, test-packages/integration-tests/test/auth-flows/auth-flow-util.ts, test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts
=> feat: Support OAuth2JWTBearer

packages/core/src/connectivity/scp-cf/connectivity-service.spec.ts, packages/core/src/connectivity/scp-cf/connectivity-service.ts
With this PR we are now able to use `onpremise_proxy_http_port` if present in the connectivity service binding, otherwise we still use the deprecated `onpremise_proxy_port`.
=> Adjust onpremise_proxy_port environment variable

packages/test-util/package.json, packages/test-util/src/test-destination-mocker.spec.ts, packages/test-util/src/test-destination-provider.spec.ts
The test-util tests were writing a lot of files with `writeFileSync` causing the tests to fail 90% of the time for me. I replaced this with `mock-fs`.
=> chore: fix flaky tests

package.json, yarn.lock
Fixes some references to vulnerable dependencies:
- color-string (although this was ok already)
- path-parse
- tar
- postcss
Closes SAP/cloud-sdk-backlog#217.
=> chore: Fix dependencies

CHANGELOG.md, knowledge-base/adr/0024-url-encoding.md, packages/core/src/odata-common/uri-conversion/get-keys.ts, packages/core/src/odata-v2/uri-conversion/odata-uri.spec.ts
Related to https://github.com/SAP/cloud-sdk-js/issues/1398.
Closes SAP/cloud-sdk-backlog#200.
=> fix: encoding OData get by key

packages/generator/package.json, packages/generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap, packages/generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap, packages/generator/src/sdk-metadata/code-sample-util.spec.ts, packages/generator/src/sdk-metadata/code-sample-util.ts, packages/generator/src/sdk-metadata/code-samples.ts, packages/generator/src/sdk-metadata/generation-and-usage.spec.ts, packages/generator/src/sdk-metadata/generation-and-usage.ts, test-packages/e2e-tests/test/metadata.spec.ts
Closes SAP/cloud-sdk-backlog#70
Updated `getApiSpecificUsage` method to generate usage code snippet for entity/function/action based on the closest match found using the levenshtein algo against a threshold.
=> feat: odata code snippet generation

CHANGELOG.md, packages/core/src/index.ts, test-packages/type-tests/test/http-agent.spec.ts
related to: https://github.com/SAP/cloud-sdk-js/issues/1568
=> fix: missing export for http-client

CHANGELOG.md, packages/core/src/http-client/http-client.spec.ts, packages/core/src/http-client/http-client.ts
Related to: https://github.com/SAP/cloud-sdk-js/issues/1564
When sending CSRF token request, the following keys of the requestConfig are now considered like the real request:
- proxy
- httpAgent
- httpsAgent
=> fix: consider http(s)Agent key when sending CSRF token requests

CHANGELOG.md, packages/core/src/odata-common/uri-conversion/get-orderby.ts, packages/core/src/odata-v2/uri-conversion/get-orderby.spec.ts, packages/core/src/odata-v4/uri-conversion/get-expand.spec.ts
Related to: https://github.com/SAP/cloud-sdk-js/issues/1575
The space of the `orderby` query parameter, for example `$orderby=Id desc`, should be encoded to `$orderby=Id%20desc`.
=> Fix: missing encoding of `orderby`

packages/generator-common/src/compiler.ts
Fixed Errors during transpilation process by ignoring the .d.ts files.
Closes SAP/cloud-sdk-backlog#256
=> fix: fix transpilation error

packages/generator-common/package.json, packages/generator-common/src/sdk-metadata/sdk-metadata.ts, packages/generator/package.json, packages/generator/src/sdk-metadata/code-sample-util.spec.ts, packages/generator/src/sdk-metadata/code-sample-util.ts, packages/openapi-generator/package.json, packages/openapi-generator/src/sdk-metadata/__snapshots__/generation-and-usage.spec.ts.snap, packages/openapi-generator/src/sdk-metadata/__snapshots__/sdk-metadata.spec.ts.snap, packages/openapi-generator/src/sdk-metadata/code-sample-util.spec.ts, packages/openapi-generator/src/sdk-metadata/code-sample-util.ts, packages/openapi-generator/src/sdk-metadata/code-sample.ts, packages/openapi-generator/src/sdk-metadata/generation-and-usage.ts, packages/openapi-generator/test/test-util.ts
Updated `getApiSpecificUsage `method to generate open-api usage code snippet for main API and its operationId based on the closest match found using the levenshtein algo measured against a threshold.
Closes SAP/cloud-sdk-backlog#245
=> feat: open-api code snippet changes

CHANGELOG.md, packages/core/src/connectivity/scp-cf/destination/destination-accessor-loading-precendence.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-accessor-provider-subscriber-lookup.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts, packages/core/src/connectivity/scp-cf/environment-accessor-types.ts, packages/core/src/connectivity/scp-cf/environment-accessor.ts, packages/core/src/connectivity/scp-cf/jwt.ts, packages/core/src/connectivity/scp-cf/token-accessor.ts, packages/core/src/odata-common/entity.ts, test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts
Closes SAP/cloud-sdk-backlog#314.
We called the `getXsuaaServiceCredentials()` multiple times in the destination-from-service.ts. This alone would be only inefficient. However, since in one case we made a call without a JWT there was no way to avoid the warning: `Could not match XSUAA instance`. This PR reduces the number of calls and also reduces the number of logs or the level. 
Note that the current XSUAA instance is mainly used to the get URL for caching. Once the xssec supports cache options this can all go away.
=> fix: Reduce number of warnings on XSUAA selection

CHANGELOG.md, packages/core/src/odata-common/selectable/edm-type-field.ts, packages/core/src/odata-common/selectable/orderable-edm-type-field.spec.ts
Closes SAP/cloud-sdk-backlog#350
Added moment() mapping for `Edm.DateTimeOffset`
=> fix: datetimeoffset ts error on creating filter

CHANGELOG.md, packages/core/src/connectivity/scp-cf/destination/destination-accessor.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-env.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-env.ts, packages/core/src/connectivity/scp-cf/destination/destination-service-types.ts
Closes SAP/cloud-sdk-backlog#286.
Enables the `forwardAuthToken` on the enviorment destinations as the [approuter](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/3cc788ebc00e40a091505c6b3fa485e7.html) also allows it.
=> feature: Auth token forwarding

test-packages/e2e-tests/package.json, yarn.lock
Related to: https://github.com/SAP/cloud-sdk-backlog/issues/310
Given that:
- `pm2` bumped `5.1.2`
- `@pm2/agent` bumped to `2.01`
for fixing the `pac-resolver` vulnerability.
However, as `pm2` uses `@pm2/agent: "~2.0.0"` and we have `@pm2/agent` as transitive dependency, I would not wait for dependabot.
=> fix: pac-resolver vulnerability

.github/workflows/build.yml, .github/workflows/tests-windows.yml, package.json
Closes SAP/cloud-sdk-backlog#304
Added new tests-windows workflow to run the tests on windows and archive the results on failure.
Adjusted `test:unit` script to pass `--ignore` workspaces correctly to lerna on windows. Added `--json --outputFile=unit-test-output.json` to jest which outputs the test results within each workspace.
=> chore: run windows test and archive

packages/core/package.json, packages/core/postinstall.js
This prints the announcement in the postinstall of the core package. I guess this does not need to be part of the 2.0 branch (yet?). I also added a way to disable the message with a env variable.
Closes SAP/cloud-sdk-backlog#230.
=> chore: Announce upgrade in postinstall

.github/workflows/tests-windows.yml, packages/generator-common/src/compiler.spec.ts
The issue was caused by windows error message handling, our test tested the concrete error message that looks like this on mac:
```
broken-src/file.ts:3:4 - error TS2588: Cannot assign to 'foo' because it is a constant
```
but it looks like this on windows:
```
Compilation Errors:·\n    D:/a/cloud-sdk-js/cloud-sdk-js/packages/generator-common/broken-src/file.ts:3:5 - error TS2588: Cannot assign to 'foo' because it is a constant.
```
Closes SAP/cloud-sdk-backlog#305.
=> fix: windows tests

CHANGELOG.md, packages/core/src/connectivity/scp-cf/cache.spec.ts, packages/core/src/connectivity/scp-cf/cache.ts, packages/core/src/connectivity/scp-cf/destination/destination-cache.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-cache.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts, packages/core/src/connectivity/scp-cf/destination/destination-service-cache.ts
- Switch the default isolation strategy from `IsolationStrategy.Tenant` to `IsolationStrategy.Tenant_User`, when setting `useCache` to true for destination lookup functions like `getDestination`.
-  Disable destination cache, when the JWT does not contain necessary information. For example, when using `IsolationStrategy.Tenant_User`, the JWT has to contain both tenant id and user id.
Closes SAP/cloud-sdk-backlog#438
Closes SAP/cloud-sdk-backlog#439
=> Fix: destination cache vulnerablity

CHANGELOG.md, packages/core/src/connectivity/scp-cf/client-credentials-token-cache.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-cache.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-cache.ts
This fixes the issue of shorter expiration times than 5 minutes. Before this if the expiration of a token was 1 min, you would have to wait for 4 mins to make the next call to the destination instead...
Relates to SAP/cloud-sdk-backlog#437.
=> fix: Overwrite default expiration times

.github/workflows/bump.yml, .github/workflows/release.yml
Explicitly checkout the `main` branch for release pipeline.
Before, as default branch, this was not necessary
=> Fix: release pipeline

CHANGELOG.md, packages/core/src/odata-common/request-builder/batch/batch-response-parser.spec.ts, packages/core/src/odata-common/request-builder/batch/batch-response-parser.ts
Closes SAP/cloud-sdk-backlog#413
If the response is HTTP 200 OK but the body is empty (delete request SF), all the empty lines after headers are trimmed (including body) and `getResponseBody` returns the last item in array, which happens to be the header and results in invalid json error. Added a check for HTTP 200 OK and Content-Length: 0 to also append an empty line at the end.
=> fix: batch DELETE response error 

CHANGELOG.md, packages/connectivity/src/scp-cf/cache.spec.ts, packages/connectivity/src/scp-cf/cache.ts, packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-cache.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.ts
This PR cherry picks the the commit #1770 and removed some deprecated functions.
=> Fix: destination cache vulnerablity #1770

.github/workflows/tests-windows.yml
This PR tries to solve the issue that the windows tests also run on `main`, in the official syntax branches are always selected by strings, so this PR changes `2.0` to `"2.0"` in an attempt to fix it.
=> fix: flaky windows tests

CHANGELOG-v2.md, packages/odata-common/src/selectable/edm-type-field.ts, packages/odata-common/src/selectable/field-builder.ts
This was deprecated and will make DeSerializer efforts easier.
This removed the FieldType from the Generics of EdmTypeField.
=> chore: Remove deprecated `FieldType` in `EdmTypeField`

scripts/check-public-api.spec.ts, scripts/check-public-api.ts
Currently the indexFiles method searches based on pattern `**/index.ts`. This will always search recursively within subfolders, which is not required for checking `checkSingleIndexFile`. This check will also fail when we have an index.ts in all sub folders. Changed the method signature to pass pattern so either `index.ts` or `**/index.ts` can be searched, depending on use case
=> chore: change method signature for indexFiles

.github/workflows/tests-windows.yml
This PR is another attempt to fix the flaky windows tests, following the previous PRs.
According to the logs, some compiled code failed, and even some tests that were changed were still running inside the windows tests, leading me to believe that the caching doesn't work as expected with the windows machines.
=> fix: windows flakyness

package.json, packages/http-client/src/__snapshots__/http-client.spec.ts.snap, packages/http-client/src/http-client.spec.ts, packages/odata-common/package.json, packages/odata-common/src/request/__snapshots__/odata-request.spec.ts.snap, packages/odata-common/src/request/odata-request.spec.ts, yarn.lock
Re-enable all odata-request tests, that were accidentally skipped.
=> chore: Run all odata-request tests

.github/workflows/build.yml, .github/workflows/bump.yml, .github/workflows/release.yml, .github/workflows/tests-windows.yml, .github/workflows/v2.yaml
This PR add node 14 test to the pipeline.
The previous blocker `@sap/edm-converters` now also supports node 14.
Follow up:
- ~apply for `main` branch as well~
=> chore: test node 14 in the pipeline

CHANGELOG.md, packages/generator/package.json, yarn.lock
The old version of this lib caused the node 14 warning.
We fixed it implicitly in the lock file by applying the upgrade by dependabot.
This PR explicitly update the version from our package.json.
=> chore: Update edm converters version explicitly

packages/connectivity/src/scp-cf/destination/destination-accessor-loading-precendence.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/token-accessor.ts
A TODO was not really clear and there was an unused argument which was removed. Relates to make this issue clearer: SAP/cloud-sdk-backlog#479
=> chore: adjust todo

knowledge-base/adr/0015-date-time-handling.md
Update date-time handling to use moment as default. Temporal will be the default after it reached stage 4.
=> chore: update date-time handling to use moment as default until temporal stage 4

packages/odata-common/src/request-builder/batch/batch-request-builder.ts, packages/odata-common/src/request/odata-delete-request-config.spec.ts, packages/odata-common/src/request/odata-get-by-key-request-config.spec.ts, packages/odata-common/src/request/odata-update-request-config.spec.ts, packages/odata-common/src/selectable/link.spec.ts, packages/odata-common/test/test-util.ts, packages/odata-v2/src/request-builder/create-request-builder.spec.ts, packages/odata-v2/src/request-builder/delete-request-builder.spec.ts, packages/odata-v2/src/request-builder/function-import-request-builder.spec.ts, packages/odata-v2/src/request-builder/get-all-request-builder.spec.ts, packages/odata-v2/src/request-builder/get-by-key-request-builder.spec.ts, packages/odata-v2/src/request-builder/update-request-builder.spec.ts, packages/odata-v2/src/uri-conversion/get-resource-path.spec.ts, packages/odata-v2/src/uri-conversion/odata-uri.spec.ts, packages/odata-v2/test/test-util.ts, packages/odata-v4/src/request-builder/delete-request-builder.spec.ts, packages/odata-v4/src/request-builder/get-all-request-builder.spec.ts, packages/odata-v4/src/request-builder/get-by-key-request-builder.spec.ts, packages/odata-v4/src/request-builder/response-transformer.spec.ts, packages/odata-v4/src/request-builder/update-request-builder.spec.ts, packages/odata-v4/test/test-util.ts, test-resources/test/test-util/test-data.ts
Improve test-utils to avoid confusion between v2/v4 entities in tests. This also fixes some incorrect usage of v2/v4 entites.
=> chore: Improve test utils

.github/workflows/codeql-analysis.yml, .github/workflows/codeql-config.yml, packages/odata-v2/src/entity.ts
relates SAP/cloud-sdk-backlog#482 When we want an exception it is good to have the tooling checked.
This PR includes a `code-ql` check on each PR. The reason the scans took so long in the past was that they scanned the docs and other useless things. After proper inclusion the scan takes 2min an runs nicely in parallel with the other checks, so I would just include it.
I created a error leading to a failing PR build:
with nice annotations on the lines where the errors are:
So I think this is a good addition to our pipeline. I kept the other triggers like schedule and merge on main so that we have security in case we do not work actively on the code.
=> chore: try scan setup

packages/odata-common/package.json, packages/odata-v2/package.json, packages/odata-v4/package.json
The `typescript` costs 60+MB, which should be used as dev dependency.
=> fix: move `typescript` to dev dependency

packages/odata-v2/package.json
In `odata-v2` package, we use e.g, `odata-common` as dependency.
When installing `odata-v2@next`, as transitive dependency, `odata-common:^2.0.0-20220107111025.0+a0f3521c` is used.
However, [semver](https://semver.npmjs.com) shows, `odata-common@2.0.0-beta.0` is chosen.
This PR is testing, whether switching to fixed version for all sdk internal dependency can solve the issue.
=> test: use fixed version for internal dependencies

.github/workflows/v2.yaml
We tested the fixed version in the previous PR: https://github.com/SAP/cloud-sdk-js/pull/1953 which did not work.
This is a new test, and hopefully the `next` versions now are newer than `2.0.0-beta.0`.
=> test: use beta 1 for next versions

packages/connectivity/package.json, packages/connectivity/src/scp-cf/cache.ts, packages/connectivity/src/scp-cf/client-credentials-token-cache.ts, packages/connectivity/src/scp-cf/destination/destination-cache.ts
Replace moment lib using in connectivity pkg for caching with Date and number. 
Closes SAP/cloud-sdk-backlog#490.
=> chore: replace moment in cache with Date and number

CHANGELOG-v2.md, packages/http-client/src/http-client-types.ts, packages/http-client/src/http-client.ts, packages/http-client/src/http-request-config.spec.ts, packages/http-client/src/http-request-config.ts, packages/http-client/src/index.ts, packages/odata-common/src/header-builder.spec.ts, packages/odata-common/src/request/odata-request.ts, packages/openapi/src/openapi-request-builder.ts
Rename origin options for http requests to lower case
=> chore: Rename origin options to lower case

CHANGELOG.md, packages/core/src/connectivity/scp-cf/authorization-header.spec.ts, packages/core/src/connectivity/scp-cf/authorization-header.ts, test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts
Related to: https://github.com/SAP/cloud-sdk-backlog/issues/510
The SDK receives the destination object from the destination service successfully for this auth type, including auth token.
However, the token is not added to the header of the real request.
This PR fixes the missing token.
Follow up:
- check the token in the header for all the auth type, which might introduce breaking changes (v2 only implementation), as the `AuthenticationType` is a type, which is gone in runtime. Use e.g., enum as alternatives.
=> fix: missing token for OAuth2Password

packages/connectivity/src/scp-cf/destination/destination-from-env.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-env.ts
With this PR the `registerDestination` function expects a different type than before, it now expects `DestinationWithName` which notifies a user at design type of a mistake.
=> fix: registerDestination with different parameter type

packages/connectivity/src/scp-cf/destination/destination-from-env.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-env.ts
This PR is a follow-up to our CAP meeting, where we decided to remove the warning.
It removes the warning and adapts the tests to it.
=> fix: Remove warning when using environment destinations

packages/connectivity/package.json, packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.ts, packages/connectivity/src/scp-cf/environment-accessor.ts, packages/connectivity/src/scp-cf/index.ts, packages/connectivity/src/scp-cf/jsonwebtoken-type.ts, packages/connectivity/src/scp-cf/jwt.ts, packages/connectivity/src/scp-cf/tenant.ts, packages/connectivity/src/scp-cf/token-accessor.ts, packages/connectivity/src/scp-cf/user.ts, packages/connectivity/src/scp-cf/xsuaa-service.ts, test-packages/type-tests/package.json, test-packages/type-tests/test/jwt.spec.ts
The `@types/jsonwebtoken` is used as dependency in the `connectivity` package, while is is a compile time dependency.
The install size of 
- `@sap-cloud-sdk/connectivity@2.0.0-beta.1-20220113152822.0` is now 8.79MB.
- `@types/jsonwebtoken` is now 1.58MB.
- I copied some instances that are necessary
- The `@types/jsonwebtoken` is moved to the test package for testing the compatibility.
=> fix: move `@types/jsonwebtoken` to type test as dev dependency

packages/analytics/README.md, packages/core/README.md, packages/eslint-config/README.md, packages/generator-common/README.md, packages/generator/README.md, packages/openapi-generator/README.md, packages/test-util/README.md, packages/util/README.md, scripts/COMMON-README-PART.md
I removed the link to stack overflow and  answers.sap.com and only keep the GH issues as suggested by Artem.
=> fix: wrong support link

packages/connectivity/src/scp-cf/authorization-header.spec.ts, packages/connectivity/src/scp-cf/authorization-header.ts
This is a cherry pick commit from #1944 .
=> fix: missing token for OAuth2Password (#1944)

packages/connectivity/src/scp-cf/cache.ts, packages/connectivity/src/scp-cf/circuit-breaker.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service-types.ts, packages/connectivity/src/scp-cf/destination/destination-service.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service.ts, test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts
Closes SAP/cloud-sdk-backlog#465.
The isolation strategy was part of the `cahcingOptions` which is missleading because it is only meaningful for the destination cache. Adjusted the API and put the `isolationStrategy` to the destination options.
I also used the `fetchDestinationOptions` along the way of our fetch methods.
=> fix: move isolation strategy to Destination API

packages/odata-v2/src/index.ts, packages/odata-v2/src/request-builder/batch-request-builder.ts, packages/odata-v2/src/request-builder/count-request-builder.ts, packages/odata-v2/src/request-builder/create-request-builder.ts, packages/odata-v2/src/request-builder/delete-request-builder.ts, packages/odata-v2/src/request-builder/get-all-request-builder.ts, packages/odata-v2/src/request-builder/get-by-key-request-builder.ts, packages/odata-v2/src/request-builder/index.ts, packages/odata-v2/src/request-builder/update-request-builder.ts, packages/odata-v4/src/index.ts, packages/odata-v4/src/request-builder/batch-request-builder.ts, packages/odata-v4/src/request-builder/count-request-builder.ts, packages/odata-v4/src/request-builder/create-request-builder.ts, packages/odata-v4/src/request-builder/delete-request-builder.ts, packages/odata-v4/src/request-builder/get-all-request-builder.ts, packages/odata-v4/src/request-builder/get-by-key-request-builder.ts, packages/odata-v4/src/request-builder/index.ts, packages/odata-v4/src/request-builder/update-request-builder.ts
Users should not **have** to write out `DefaultDeSerializers` at any time. Before this PR, in some cases, they would have to do this. Therefore I added defaults to the types
Relates to SAP/cloud-sdk-backlog#515.
=> Add default (de-)serializers to the request builders

packages/odata-common/src/filter/filterable.ts, packages/odata-common/src/index.ts, packages/odata-v2/src/common.ts, packages/odata-v4/src/common.ts
This exports the and, or and not functions from the odata version specific packages instead of common.
Additionally, those are not marked as @internal anymore.
Closes SAP/cloud-sdk-backlog#515.
=> chore: Export and, or, not from odata-vX packages

scripts/check-licenses.ts
In the discussion about code scanning tools to used, I realized that the list of licences is a bit too broad. Luckily there we did not use any of the GPL in production code, only in some test libs.
=> chore: make allowed licences more strict

package.json, yarn.lock
`json-schema` is vulnerable to prototype pollution before version 0.4.0. This PR fixes its resolution to a non-vulnerable version.
=> Fix json-schema resolution

.github/workflows/v2.yaml
The e2e-test is missing as prerequisites of v2 canary release.
=> fix: v2 pipeline

package.json, packages/generator/package.json
`execa` is used:
- as dependency in the `generator` package, while only tests are using it.
- in some scripts of the `script` directory, which is for the SDK developers like calling `lerna` or generating readme.
This lib is also related to the ESM issue.
If we don't ship it to the users, even it might be vulnerable in the future, we are still "safe".
This PR will move the `execa` to dev dependency.
226 KB
=> fix: move `execa` to dev dependency

.github/workflows/build.yml
This PR adds the dependabot automerge job in the build workflow for the main branch
=> chore: add dependabot automerge for main branch

CHANGELOG-v2.md, packages/http-client/package.json, packages/http-client/src/http-client-types.ts, packages/http-client/src/http-client.spec.ts, packages/http-client/src/http-client.ts, packages/openapi/src/openapi-request-builder.ts
Closes SAP/cloud-sdk-backlog#524.
Changed the default value of `fetchCsrfToken` to true for the generic http client for non-GET requests.( note: this was already true by default in the odata and openapi clients). The user can still override this by passing false in the `executeHttpRequest` method.
=> chore: change fetchCsrfToken default value to true

CHANGELOG.md, packages/core/src/connectivity/scp-cf/destination/destination-accessor-proxy-configuration.spec.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-env.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts, packages/core/src/connectivity/scp-cf/destination/destination-from-vcap.ts, packages/core/src/connectivity/scp-cf/destination/destination-service-types.ts, packages/core/src/http-agent/proxy-util.spec.ts, packages/core/src/http-agent/proxy-util.ts, test-packages/integration-tests/test/auth-flows/auth-flow-util.ts, test-packages/integration-tests/test/auth-flows/auth-flow.spec.ts
This PR is a copy of #2026 
Some adaptions were made to support main (e.g. different getDestination call, different imports)
=> chore: Add support for proxy type privatelink

packages/generator/package.json, packages/generator/src/generator.spec.ts, packages/generator/src/generator.ts, packages/generator/src/service/package-json.spec.ts, packages/generator/src/service/package-json.ts
Add dependencies to generator + recommendation if the odata package was not installed.
The idea is: This will work for the local generator, but if someone is using a globally installed generator, they must install the odata packages.
I am not too happy about the tests, but I think this is a general problem in the odata generator...
Closes SAP/cloud-sdk-backlog#562.
=> Generator fixes

.github/workflows/bump.yml
This is used for one time major version release, and will be reverted after the release.
Having release in the pipeline/container is much cleaner/saver instead of local.
=> chore: support releasing major version

.github/workflows/v2.yaml
After releasing 2.0.0, new `next` versions are released with `3.0.0...` prefixes.
These versions might be risky when developing 3.0, as dynamic versioning can cause unexpected logics.
It's possible to `unpublish` them within 72 hours as long as no packages depend on them.
I successfully deleted test-util, but not for connectivity.
The idea is to publish new `next` versions, so potentially `3.0.0...` versions are free.
=> chore: publish a new next version

.github/workflows/v2.yaml
Reverts SAP/cloud-sdk-js#2104
The one time release was done, so revert the changes.
=> Revert "chore: publish a new next version"

packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/destination/destination-selection-strategies.ts
The `DestinationSelectionStrategies` is used by CAP.
=> fix: re-export `DestinationSelectionStrategies`

.github/workflows/build.yml
=> chore: disable publishing canary for v1

.github/workflows/1.0-build.yml, .github/workflows/tests-windows.yml
It seems the 1.0-main build is only triggered, when the pipeline is shown in it's branch instead of the default one.
=> fix: 1.0 pipeline

.github/workflows/blackduck.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/tests-windows.yml
The removed v1 pipelines should be set up in `1.0-main` branch to make it work.
=> chore: remove useless v1 pipelines

CHANGELOG.md, packages/openapi-generator/package.json, packages/openapi-generator/src/generator.ts
Fix transpilation errors during generation.
Closes SAP/cloud-sdk-backlog#578.
=> fix: Add OpenAPI dependency

packages/generator/src/edmx-to-vdm/common/action-function-return-types.ts, packages/generator/src/edmx-to-vdm/common/complex-type.ts, packages/generator/src/edmx-to-vdm/common/entity.ts, packages/generator/src/edmx-to-vdm/edmx-to-vdm-util.ts, packages/generator/src/edmx-to-vdm/v2/complex-type.ts, packages/generator/src/edmx-to-vdm/v2/entity.ts, packages/generator/src/edmx-to-vdm/v2/function-import.ts, packages/generator/src/edmx-to-vdm/v2/service-entities.ts, packages/generator/src/edmx-to-vdm/v4/action-import.ts, packages/generator/src/edmx-to-vdm/v4/complex-type.ts, packages/generator/src/edmx-to-vdm/v4/entity.ts, packages/generator/src/edmx-to-vdm/v4/function-import.ts, packages/generator/src/edmx-to-vdm/v4/service-entities.ts, packages/generator/src/service-generator.spec.ts, packages/generator/src/service-name-formatter.ts, packages/generator/src/vdm-types.ts, packages/generator/test/test-util/data-model.ts
Closes SAP/cloud-sdk-backlog#521.
This PR removes the `includeFactoryName` method and the `factoryName` property from the `VdmComplexType`
=> chore: todo remove includeFactoryName function

.github/workflows/blackduck.yml
This PR switches our Blackduck scans from a per-branch scan to nightly scans, to avoid hitting the performance threshold.
Closes SAP/cloud-sdk-backlog#574.
=> fix: Blackduck performance threshold

CHANGELOG.md, packages/generator-common/src/file-writer/index.ts, packages/generator-common/src/file-writer/package-json.ts, packages/generator/src/generator-options.ts, packages/generator/src/generator.ts, packages/generator/src/service/package-json.spec.ts, packages/generator/src/service/package-json.ts, packages/openapi-generator/README.md, packages/openapi-generator/src/file-serializer/__snapshots__/package-json.spec.ts.snap, packages/openapi-generator/src/file-serializer/package-json.spec.ts, packages/openapi-generator/src/file-serializer/package-json.ts, packages/openapi-generator/src/generator.ts, packages/openapi-generator/src/options/generator-options.ts, packages/openapi-generator/src/options/options.ts, test-packages/test-services/openapi/no-schema-service/package.json, test-packages/test-services/openapi/swagger-yaml-service/package.json, test-packages/test-services/openapi/test-service/package.json
Relates SAP/cloud-sdk-backlog#583.
we need an option to set the license for our generated clients. This PR adds the CLI option to set the license propert in the generate `package.json`.
=> feat: Allow specifying the license for generated clients

packages/generator-common/src/file-writer/package-json.ts, packages/generator/src/service/package-json.ts, scripts/check-public-api-cli.ts
Re-enabled many public-api checks, which were left commented out from an old PR.
=> chore: re-enable public api checks

packages/connectivity/src/scp-cf/resilience-options.spec.ts, packages/connectivity/src/scp-cf/resilience-options.ts
E2E generator tests failed due to the error below, because we use `@types/opossum` code in the `d.ts` file, while the dependency is a dev dependency.
```
[2022-03-21T16:59:39.858Z] ERROR    (generator-cli): ErrorWithCause: Generation of services failed.
at /.../node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js:22:18
Caused by:
Error: Compilation Errors:
/.../node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/resilience-options.d.ts:1:27 - error TS7016: [object Object]
at transpileDirectory (/.../node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:35:15)
at async Promise.all (index 0)
at async generate (/.../node_modules/@sap-cloud-sdk/generator/dist/generator.js:52:13)
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
```
This PR removes the type …
=> fix: generator compilation error

CHANGELOG.md, packages/http-client/src/http-request-config.spec.ts, packages/http-client/src/http-request-config.ts, packages/odata-common/src/request/odata-request.spec.ts, packages/odata-common/src/request/odata-request.ts, packages/openapi/src/openapi-request-builder.spec.ts, packages/openapi/src/openapi-request-builder.ts
Closes SAP/cloud-sdk-backlog#71.
Remove `method` from `defaultDisallowedKeys` in `http-request` to support custom http request method. 
Overwrite http `method` in `odata-common` and `openapi` if it is defined in custom http configuration.
The usage should look like
```typescript
const { myEntityApi } = myEntityService();
myEntityApi
.requestBuilder()
.getAll()
.addCustomRequestConfiguration({ method: 'YOUR-METHOD' });
```
By default, http method is set to `get` by `getAll()`. Now, it will be overwritten by `YOUR-METHOD`.
TODO:
=> Support custom request config for method in OData and OpenAPI

packages/generator/src/service/package-json.spec.ts, packages/generator/src/service/package-json.ts, packages/openapi-generator/src/file-serializer/__snapshots__/package-json.spec.ts.snap, packages/openapi-generator/src/file-serializer/package-json.ts, test-packages/test-services/openapi/no-schema-service/package.json, test-packages/test-services/openapi/swagger-yaml-service/package.json, test-packages/test-services/openapi/test-service/package.json
The peerDependencies are not necessary as the same dependencies are declared already.
=> chore: Remove peerDeps in generated clients

.github/dependabot.yml
=> chore: disable dependabot for v1 main

test-packages/e2e-tests/package.json, test-packages/e2e-tests/srv/test-service.js, yarn.lock
It seems 4.5.x patch version introduces the breaking change:
- cds-dk 4.5.0 works
- cds-dk 4.5.4 not
=> chore: update cds-dk to 4.9.3

packages/generator/src/generator.ts, packages/openapi-generator/src/options/options.ts
Glob package included option `allowWindowsEscape` (from `minimist` package) which always treats `\` in patterns as escapes, not path separators. They have recommended to use `/` as path separators. 
Because of this, the `new GlobSync(pattern)` stopped working as expected and couldn't find any files.
=> fix: fix windows test

.github/workflows/1.0-build.yml
Apr. 30 is the last day of node 12 support.
Node [reference](https://nodejs.org/en/about/releases/).
=> chore: only test node 14 for sdk 1.0

.github/workflows/tests-windows.yml
Seems like yarn or turborepo behave differently on windows and need additional `--` to pass the args to the actual executable.
If you have a windows computer, feel free to test the following commands (they work on mac but that didnt help with my previous fix):
- `yarn test:unit --continue -- -- -- --json --outputFile=unit-test-output.json`
- `yarn test:integration -- -- -- --json --outputFile=int-test-output.json`
=> fix: Adjust how arguments are passed to jest

package.json
The convenient scripts were removed.
I would like to keep them so I can e.g., start the e2e test app with a shorter command.
=> chore: revert the workspace scripts removal

.github/workflows/memory-tests.yml
It was enabled for testing on the initial PR, but should be removed now.
=> chore: disable memory tests from PR builds

.changeset/config.json, .github/workflows/build.yml, canary-release-changeset.md
Currently the canary release does nothing, because there is no [snapshot version id created](https://github.com/SAP/cloud-sdk-js/runs/6285802719?check_suite_focus=true):
In this PR I used the [build in function of changeset](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md).
However, this would lead to versions 0.0.0-{tag}-DATETIMESTAMP instead of 2.3.0-{tag}-DATETIMESTAMP. Since the tag is used to identify and all version are changed this should work:
However I am not sure if this a beautiful thing to do. On the other hand if we start having separate version on the different packages it could become difficult to take the latest version and add some timestamp postfix since each package potentially has a different version.
=> fix: canary release

.github/workflows/build.yml
When running the check just after checkout, the irrelavant files (node_modules) would not be a problem.
See example [here](https://github.com/fsfe/reuse-action#example-usage).
=> fix: reuse check

.github/workflows/build.yml
We had a small mistake, that if no changeset is there the `rm` fails in the canary release. This adds the `-f` option to it so this does not happen.
=> fix: do not fail if files are not there

packages/connectivity/package.json, packages/generator-common/package.json, packages/generator/package.json, packages/http-client/package.json, packages/odata-common/package.json, packages/odata-v2/package.json, packages/odata-v4/package.json, packages/openapi-generator/package.json, packages/openapi/package.json, packages/temporal-de-serializers/package.json, packages/test-util/package.json, packages/util/package.json, test-packages/e2e-tests/package.json, test-packages/integration-tests/package.json
This PR sets the TIMING env var correctly for windows. 
Currently, running the `lint:fix` command gives the following error on windows:
> 'TIMING' is not recognized as an internal or external command
Note: Please test if this also works on mac.
=> fix: TIMING env var is set on windows

CHANGELOG.md, scripts/merge-changelogs.ts
For example, the message type `Compatibility Note` will be transformed into the header `Compatibility Notes`.
Also, it seems that `Known Issue` was missing, so I added it.
=> chore: pluralize the changelog headers

package.json, scripts/deprecate-npm-package.ts
This script was used for deprecating all v1 core packages, which will be useful in the future (e.g., deprecating v2 cores).
=> chore: add a script for npm package deprecation

.changeset/miss-schnitzel.md, packages/http-client/src/http-client.spec.ts, packages/http-client/src/http-client.ts
Before, we list all the custom headers in the warning, however, not every header will overwrite something.
Now, we only show headers that are overwritten by custom headers.
=> fix: only show warning when overwriting headers

scripts/npm-stats.ts
I added all the published packages to the list so we understand the trend of:
- our internal download
- `odata-v2` download
- `generator` download
- `connectivity` download
=> chore: record more download statistics

packages/odata-common/src/filter/filterable.ts, packages/odata-v4/src/entity.ts, test-packages/type-tests/test/v4/filters.spec.ts
Closes SAP/cloud-sdk-backlog#691.
So I give up, I do not understand why it works for V2 and not for v4 on a deep level. The change to the `Entity` in this PR  was not relevant. On the play ground I did the following:
- Create a minimal example for an Entity with a single 1:1 nav prop no enum, complex type what so ever
- Align deserializers for v2 and v4 and types
- Remove one-to-many type also from filterable
- Align entity (version is v2 for both)
The error remains only for v4 not for v2 using the reduced example.
I knew from the investigation and tests that the default value set to any fixes it, but this leaves a bitter taste because I do not see why, WHY, WHYYYY but I have to accept that I do not see the reason.....
=> fix: type issue

CHANGELOG.md
Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/751
Just added a s for some heading in the release notes.
=> chore: Pluralize headings release Note

packages/http-client/src/http-client.spec.ts
An explicit test is added for testing `$abc` as a key of query parameter of the http client, although it was covered by the odata cases.
related to: https://github.com/SAP/cloud-sdk-js/issues/2561
=> chore: add a test for special char in http client

packages/connectivity/src/scp-cf/destination/__snapshots__/destination-from-vcap.spec.ts.snap, packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts, packages/connectivity/src/scp-cf/destination/service-binding-to-destination.ts, packages/connectivity/src/scp-cf/token-accessor.ts
A small fix the for @mr-flannery we check the XSUAA only when cache is on. Only then we use the URL to build the cache key.
=> fix: move xsuaa only when cache is needed

.changeset/few-zoos-repeat.md, packages/openapi-generator/src/generator.spec.ts, packages/openapi-generator/src/generator.ts, packages/openapi-generator/src/options/options-per-service.spec.ts, packages/openapi-generator/src/options/options-per-service.ts
Relates https://github.com/SAP/cloud-sdk-backlog/issues/803
1. I changed an error message for duplicated specification files to notify users should use options for avoiding the error.
2. I changed `getInputFilePaths()` to enable the function to accept glob expression as an argument as well.
=> feat: Improve OpenAPI generator input handling

packages/connectivity/src/scp-cf/cache.spec.ts, packages/connectivity/src/scp-cf/cache.ts, packages/connectivity/src/scp-cf/destination/destination-cache.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.ts, packages/connectivity/src/scp-cf/jwt.ts
Closes https://github.com/SAP/cloud-sdk-backlog/issues/534
Make `Cache` class just accepts milliseconds instead of `DateInputObject` like `new Cache<T>(validityTime?: number)`
1. Changed `validityTime` to `number`
2. Removed interface `DateInputObject`
3. Adjusted other parts that use Cache class with `DateInputObject`
=> refactor: set validitytime in cache as milliseconds

packages/openapi-generator/package.json, packages/openapi-generator/src/generator.spec.ts, packages/openapi-generator/src/generator.ts
Closes https://github.com/SAP/cloud-sdk-backlog/issues/416
As this [comment](https://github.com/SAP/cloud-sdk-backlog/issues/416#issuecomment-1191386388) about the root cause, the problem is `fs.rmdir(path, { recursive: true })` is used in `generator()`that will be deprecated in future Node versions. 
1. Changed `fs.rmdir` to ~~`fs.rm`~~ which will be supported in future versions.
2. Added --clearOutputDir in a test of a file creating process to test this issue.
Since `fs.rm` is not supported in Node v12, I use `fs-extra` instead of it.
=> fix: OpenAPI generator should create output directory

packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts
We have a duplicated type `DestinationForServiceBinding**s**Options` for `DestinationForServiceBindingOptions`. The name is fixed in this PR.
=> fix: typo in destination for service binding options

packages/openapi-generator/src/generator.spec.ts, packages/openapi-generator/src/generator.ts, packages/openapi-generator/src/options/generator-options.spec.ts, packages/openapi-generator/src/options/options.ts
The generation of openapi- clients fails on Windows when globs are used as input.
On Windows, `\\` is used as path separator, however only `/` character is used by  glob implementation. This PR adjusts the glob pattern passed as input to the openapi-generator.
=> fix: glob pattern in openapi-generator on windows

.changeset/2.0-fix.md, packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/environment-accessor-types.ts, packages/connectivity/src/scp-cf/token-accessor.ts
This is a partial revert of https://github.com/SAP/cloud-sdk-js/pull/1898, as this parameter is "used".
=> Fix: `serviceToken` so it accepts `XsuaaServiceCredentials` again.

.changeset/tasty-kiwis-flash.md, packages/connectivity/src/scp-cf/destination/__snapshots__/destination-from-vcap.spec.ts.snap, packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts, packages/connectivity/src/scp-cf/destination/service-binding-to-destination.ts
Relates SAP/cloud-sdk-backlog#825
Adds the support to call the xsuaa api as requested here: https://answers.sap.com/questions/13693817/sap-cloud-sdk-javascript-client-credential-flow.html
=> feat: add support for xsuaa api

packages/mail-client/src/mail-client-types.ts, packages/mail-client/src/mail-client.spec.ts
This key is mandatory for some mail servers 🤷
=> feat: support send html body of emails

packages/connectivity/src/scp-cf/connectivity-service.ts, packages/mail-client/package.json, packages/mail-client/src/mail-client.spec.ts, packages/mail-client/src/mail-client.ts, yarn.lock
When using `socks@2.7.0`  (with `nodemailer`) for creating socket connection, it failed.
As it's working with `socks@2.6.2`, let's stick to the old version for now.
Also, there is a type fix about port.
=> fix: use socks 2.6.2

packages/mail-client/src/mail-client.spec.ts, packages/mail-client/src/mail-client.ts
There is a typo (`proxy-authorization` vs `proxy-authentication`), which was not detected during compile time 🤷 , even the key was defined in the type.
=> fix: proxy authentication typo for sending mails

test-packages/type-tests/test/v2/schema-properties.spec.ts, test-packages/type-tests/test/v4/schema-properties.spec.ts
Closes SAP/cloud-sdk-backlog#672.
I added some type tests for the schema properties for both v2 and v4. Each version contains five different properties, which should have enough coverage for the type test.
=> chore: add type tests for OData properties of schema

.github/workflows/build.yml
Closes SAP/cloud-sdk-backlog#836.
I changed the trigger event for the canary release to `schedule` and `workflow_dispatch`.
`workflow_dispatch`: The input `canary-release` variable will switch on/off the canary release.
Please double-check the `schedule` time to make it work with the nightly e2e test.
As required, the canary release (for both `schedule` and `workflow_dispatch`) will only happen if the `canary-release-pre-check` was successful, i.e., there were new commits during the last 24 hrs. Otherwise, after running all checks and tests, the actual `canary-release` workflow will be skipped. See [passing job outputs to another job](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job).
=> chore: trigger canary release nightly or on demand

.changeset/slow-emus-drum.md, packages/util/package.json, packages/util/src/logger/cloud-sdk-logger.spec.ts, packages/util/src/logger/cloud-sdk-logger.ts
Closes [#367](https://github.com/SAP/cloud-sdk-backlog/issues/367)
This added a new method that enables users to set transport globally. When the user sets the global transport, all transports in all loggers including default loggers are replaced with the global transport.
example
```
const fileTransport = new winston.transports.File({
filename: "info.log",
level: "info",
});
const httpTransport = new winston.transports.Http({
host: "localhost",
port: 8080,
});
setGlobalTransports([fileTransport, streamTransport]);
```
- made a new method `setGlobalTransports()` that sets transports globally
- added tests for the new function
- added dependency for the new function
=> feat: set global transport

.changeset/chips-and-fish.md, packages/mail-client/src/index.ts, packages/mail-client/src/mail-client-types.ts, packages/mail-client/src/mail-client.spec.ts, packages/mail-client/src/mail-client.ts, test-packages/e2e-tests/test/mail/mail.spec.ts, test-packages/type-tests/test/mail-client/mail-client.spec.ts
Reverts SAP/cloud-sdk-js#2861
@marikaner , as discussed, let's revert and merge next week, so the nightly e2e tests are free.
=> Revert "feat: export SMTP transport options of `nodemailer`"

scripts/add-changelog.ts
Relates SAP/cloud-sdk-backlog#841.
As in the title. Added replacement of `##` to `###` to mathc style in target document:https://raw.githubusercontent.com/SAP/cloud-sdk/main/docs-js/release-notes.mdx
=> chore: Add link API Reference to ReleaseNotes

packages/connectivity/src/scp-cf/cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts, packages/openapi-generator/src/generator.ts
We have a customer issue, where destination are chaced forever, I just double checked the tests we have and I guess this is not the case - perhaps the token lifetime on the customer side is too long. Since I went over the test I made some small improvements.
=> chore: Improve destination cache tests

test-packages/e2e-tests/test/mail/mail.spec.ts
For the test of sending multiple emails, we can send `10` emails instead of `100`, which should be faster and more stable.
=> Improve: mail e2e

packages/generator-common/src/compiler.ts
In some cases our compiler created error messages such as:
```
Caused by:
Error: Compilation Errors:
.../Foo.ts:2:772 - error TS7053: [object Object]
```
This commit fixes that by selecting the string property if the object containing the error is not a string.
=> Improve error messages in ts compiler

packages/connectivity/src/scp-cf/destination/http-proxy-util.ts, packages/connectivity/src/scp-cf/get-protocol.ts, packages/connectivity/src/scp-cf/protocol.ts
Closes [SAP/cloud-sdk-backlog#883](https://github.com/SAP/cloud-sdk-backlog/issues/883)
This fixes 2 issues in our API docs module section.
this comes from that typedoc wrongly recognizes the internal namespace [`Protocol`](https://github.com/SAP/cloud-sdk-js/blob/b7344eb5c737984de5dff3f0948e6e343e2ab15c/packages/connectivity/src/scp-cf/protocol.ts#L14) is exported instead it has `@internal` tag. That's because the same name enum [`Protocol`](https://github.com/SAP/cloud-sdk-js/blob/b7344eb5c737984de5dff3f0948e6e343e2ab15c/packages/connectivity/src/scp-cf/protocol.ts#L6) is exported in the same file then typedoc see the internal namespace as exported one. the namespace `Protocol` and the enum `Protocol` must have different names. ~~this changed the namespace name to the identifiable name …
=> fix: API docs module section issues

packages/odata-common/src/properties-util.spec.ts, packages/odata-v2/src/properties-util.spec.ts, packages/odata-v2/src/uri-conversion/get-expand.spec.ts, packages/odata-v2/src/uri-conversion/get-select.spec.ts, packages/odata-v2/src/uri-conversion/get-select.ts, packages/odata-v4/src/properties-util.spec.ts, packages/odata-v4/src/uri-conversion/get-expand.spec.ts, packages/odata-v4/src/uri-conversion/get-select.spec.ts
Closes SAP/cloud-sdk-backlog#463.
this adds explicit tests for `getSelect()`, `getExpand()` and also `properties-util.ts`
=> improve: add explicit tests for `getSelect()`, `getExpand()` and `properties-util.ts`

README.md
npm package name correction: @sap-cloud-sdk/conectivity to @sap-cloud-sdk/connectivity
Typo correction in npm package name
=> fix: a readme typo

packages/connectivity/README.md, packages/eslint-config/README.md, packages/generator-common/README.md, packages/generator/README.md, packages/http-client/README.md, packages/mail-client/README.md, packages/odata-common/README.md, packages/odata-v2/README.md, packages/odata-v4/README.md, packages/openapi-generator/README.md, packages/openapi/README.md, packages/temporal-de-serializers/README.md, packages/test-util/README.md, packages/util/README.md, scripts/COMMON-README-PART.md
Closes https://github.com/SAP/cloud-sdk-backlog/issues/889
this updates broken API doc links
=> fix: update broken API doc links

packages/odata-v2/src/request-builder/create-request-builder.spec.ts, test-packages/integration-tests/test/test-data/batch-sub-requests.ts, test-packages/integration-tests/test/test-data/batch/changeset-request.ts, test-packages/integration-tests/test/test-data/batch/requests.ts, test-packages/integration-tests/test/v2/batch.spec.ts
Related to: https://github.com/SAP/cloud-sdk-backlog/issues/943
Added some tests for using `appendPath`:
- with create requests
- with batch requests
=> chore: add tests for using `appendPath`

.github/dependabot.yml
=> chore: enable dependabot for 2 branches

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Since we don't need to support smaller versions we should update the devcontainer.
=> Update node version in devcontainer to 18

.github/dependabot.yml
Should be merged after https://github.com/SAP/cloud-sdk-js/pull/3154
=> Configure dependabot to update axios on v3 branch

.github/workflows/bump.yml
=> chore: Fix v2-main bump workflow

.github/workflows/next-build-nightly.yml
When using `v2-main` branch as default branch, the nightly job pipeline should also be located on the `v2-branch`
=> chore: Fix nightly `next` release

packages/resilience/src/retry.ts
Without this return jest reported open handlers after the test finished.
Follow up for #3213
=> chore: Return something on bail in retry middleware

.github/workflows/build.yml, major-release-changeset.md
Tackel prerelease problem introducing a 3.0.0 prerelease version. Currently the `next` tag points to a version 2.11.0-20221220 which fine in principle: https://www.npmjs.com/package/@sap-cloud-sdk/util?activeTab=versions
However, in the dependencies the changeset bumps to the next version which is 2.12.0. This is however a valid version two release now. Since it is missleading to use version 2.X.Y for version 3 prereleases this change will release a version 3.0.0-20221220 with the tag next.
=> chore: Release Major Canary

.github/workflows/next-build-nightly.yml, major-release-changeset.md
The nightly run kept adding version with 2.11.0-123456 as next release:
https://github.com/SAP/cloud-sdk-js/actions/runs/3784638566
This PR fixes that. I found it strange that the next release was not triggered from a file on the new `main`branch. The change should be the same as in the build file right now:
https://github.com/SAP/cloud-sdk-js/blob/e3444b46d19af40c4671b575c5b27918991558a3/.github/workflows/build.yml#L160
=> chore: Fix Nightly Next Release

.changeset/purple-ties-lie.md, .changeset/yellow-schools-watch.md, packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-cache.ts, packages/connectivity/src/scp-cf/destination/destination-from-registration.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.ts, packages/connectivity/src/scp-cf/destination/destination-service-types.ts, test-packages/integration-tests/test/cache.spec.ts
Replacing enum with strings.
Relates to SAP/cloud-sdk-backlog#1014.
=> chore!: Replace enum `IsolationStrategy` with string literal union type

packages/openapi-generator/src/options/generator-options.ts, packages/openapi-generator/src/options/options.ts
Relates SAP/cloud-sdk-backlog#978.
Adds the deprecation also to the OpenApi options - they were partially hidden but it is always nicer to do that.
=> chore: Add Deprecation for Openapi Generator Options

.changeset/odata-v2-update-string-null.md, packages/odata-v2/src/request-builder/update-request-builder.spec.ts, packages/odata-v2/src/request-builder/update-request-builder.ts
Relates to https://github.com/SAP/cloud-sdk-backlog/issues/1003.
=> fix: Update Request Builder filters out updates to null

.eslintrc.js
We got rid of enums in 0bc120593d66f6dc198d27f58e0ceb4547625cfa because we learned that they behave in unexpected ways in TypeScript and don't add much value. This lint rule will make us aware of this in the future in case someone accidentally wants to introduce new enums.
=> chore: Configure lint to not allow enums

.changeset/calm-taxis-cross.md, V3-Upgrade-Guide.md, packages/generator/src/generator-options.ts, packages/generator/src/generator.ts, packages/generator/src/service/package-json.spec.ts, packages/generator/src/service/package-json.ts, packages/generator/src/service/readme.ts, packages/generator/test/test-util/create-generator-options.ts, test-packages/test-services-e2e/generate-e2e-services.ts, test-packages/test-services-odata-v2/generate-odata-services.ts, test-packages/test-services-odata-v4/generate-odata-services.ts
Relates  SAP/cloud-sdk-backlog#978.
Removed the remaining deprecated options after in #3312 and #3309 the first bunch was removed.
=> chore!: Remove Remaining Deprecated Options

package.json, yarn.lock
This reverts commit cc1d4de13b161d2ef06e24ce50c0bf362da5d418.
It seems like this upgrade caused our build to be unreliable.
=> chore: Revert "chore(deps-dev): bump turbo from 1.6.3 to 1.7.0 (#3340)"

.changeset/fair-carrots-grow.md, packages/generator/package.json
This PR fixes the link to our generator binary, which was renamed and therefore the link needed to be changed as well.
=> fix: binary link to generator

.github/workflows/api-docs.yml
This adds the workflow_dispatch property to this workflow on v2-main and enables that it can be manually triggered from the Actions tab.
=> chore: Add manual workflow trigger

packages/generator/src/cli.ts, packages/generator/src/generator.ts, packages/generator/src/service-name-formatter.spec.ts, packages/generator/src/service-name-formatter.ts
Closes SAP/cloud-sdk-backlog#1071.
Remove the `parsing args` log statement. Keep the `successful` generated line so that at least one line is printed when everything worked out.
Also set one info level to warn to be a bit more consistent with other warning messages.
=> chore: Adjust log level of generator

packages/generator/src/options/options.ts, packages/openapi-generator/src/cli-parser.ts, packages/openapi-generator/src/generator.ts, packages/openapi-generator/src/index.ts, packages/openapi-generator/src/options/options.ts, test-packages/test-services-openapi/generate-openapi-services.ts, test-packages/test-services-openapi/package.json
I noticed that the `GeneratorOptions` type disappeared, probably when merging the OData and OpenAPI options. In this PR we reexpose the Options from the OpenAPI generator.
=> chore: reexpose openapi generator options

.changeset/light-radios-sparkle.md, .changeset/many-hairs-build.md, packages/connectivity/src/http-agent/http-agent.spec.ts, packages/connectivity/src/http-agent/http-agent.ts
=> fix: send certs only for MTLS authentication

.changeset/tricky-suits-appear.md, packages/http-client/src/csrf-token-middleware.spec.ts, packages/http-client/src/http-client.spec.ts, packages/resilience/src/circuit-breaker.spec.ts, packages/resilience/src/circuit-breaker.ts, packages/resilience/src/index.ts, packages/resilience/src/resilience.spec.ts, packages/resilience/src/resilience.ts, packages/resilience/src/retry.ts, packages/resilience/src/timeout.ts
We named the `circuitBreaker()` function `circuitBreakerHttp()` by error. This PR deprecates the erroneous name and replaces it with the corrected one.
=> fix: fix circuit breaker export

.github/workflows/blackduck.yml, .github/workflows/bump.yml, .github/workflows/downloads.yml, .github/workflows/lint.yml, .github/workflows/memory-tests.yml, .github/workflows/release.yml, .github/workflows/tests-windows.yml
With this PR the node version increases in several of our GitHub actions to version 18.
This should also fix the current error in the downloads action.
=> chore: download stats action

test-packages/e2e-tests/test/generator.config.json
Without this option, repeated e2e test runs will fail.
=> chore: Configure generator in e2e tests to overwrite old files

.changeset/swift-berries-hide.md, packages/mail-client/src/mail-client.spec.ts, packages/mail-client/src/mail-client.ts
The step results in the following error:
`Error from nodemailer \"Error: Invalid greeting. response=250-mail07.wdf.sap.corp\n250-PIPELINING\n250-SIZE 307200000\n250-VRFY\n250-ETRN\n250-STARTTLS\n250-ENHANCEDSTATUSCODES\n250-8BITMIME\n250-DSN\n250-SMTPUTF8\n250 CHUNKING: 250-mail07.wdf.sap.corp\n250-PIPELINING\n250-SIZE 307200000\n250-VRFY\n250-ETRN\n250-STARTTLS\n250-ENHANCEDSTATUSCODES\n250-8BITMIME\n250-DSN\n250-SMTPUTF8\n250 CHUNKING\`
=> fix: Remove transport.verify step before sending email

package.json
Fixes the following issue on running bump script:
```
$ yarn generate --force && yarn doc && ts-node scripts/after-bump.ts
$ turbo run generate --force --force
ERROR the argument '--force' cannot be used multiple times
```
=> chore: Fix turbo --force error

packages/resilience/package.json
I think these dependencies were added to the wrong category by accident. I don't see a reason to make them productive dependencies.
=> chore: Move dependencies to dev dependencies

.changeset/lazy-carpets-marry.md, packages/odata-common/src/entity-builder.spec.ts, packages/odata-common/src/entity-builder.ts
Fix the `FromJsonType` to allow nullable arrays. This should accomodate a breaking change from TypeScript.
=> fix: Fix `FromJsonType`

.changeset/strong-ducks-cheat.md, packages/resilience/src/circuit-breaker.ts
This should fix the issue identified by the E2E tests + Tom, where the types for 'opossum' cannot be found.
=> fix: fix types for transpilation on generation

.changeset/small-news-roll.md, packages/resilience/src/resilience.spec.ts, packages/resilience/src/retry.spec.ts, packages/resilience/src/retry.ts
With this PR, a  parsing error when the last response in a chain of retries returned undefined, is fixed.
=> fix: Resilience undefined handling

.github/workflows/build.yml
This PR should fix the failing canary builds, according to [this](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages).
=> chore: Fix canary build

.changeset/tasty-ties-give.md, packages/http-client/src/csrf-token-middleware.spec.ts, packages/http-client/src/csrf-token-middleware.ts
With this PR, we stop sending the request's data when requesting a CSRF token, which caused issues for users who were sending large requests (see [issue](https://github.com/SAP/cloud-sdk-js/issues/3846))
=> fix: csrf token fetching

packages/connectivity/src/scp-cf/authorization-header.spec.ts, packages/connectivity/src/scp-cf/authorization-header.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-authentication-type.spec.ts
Closes SAP/cloud-sdk-backlog#1112.
=> chore: add `x-sap-security-session: create` for SAMLAssertion

.changeset/selfish-needles-grow.md, packages/connectivity/src/scp-cf/destination/destination-from-registration.ts, packages/connectivity/src/scp-cf/destination/destination-service-types.ts, packages/connectivity/src/scp-cf/destination/service-binding-to-destination.ts
The `expiresIn` property of a Destination’s auth tokens can be undefined. This PR fixes this.
=> feat: Fix expires in property

.changeset/chilly-poets-walk.md, .changeset/lazy-cougars-dream.md, packages/connectivity/package.json, packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-provider-subscriber-lookup.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-proxy-configuration.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-types.ts, packages/connectivity/src/scp-cf/destination/destination-from-env.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-env.ts, packages/connectivity/src/scp-cf/destination/destination-from-registration.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-registration.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts, packages/connectivity/src/scp-cf/destination/destination.spec.ts, packages/connectivity/src/scp-cf/destination/destination.ts, packages/connectivity/src/scp-cf/destination/forward-auth-token.spec.ts, packages/connectivity/src/scp-cf/destination/forward-auth-token.ts, packages/connectivity/src/scp-cf/destination/index.ts, packages/connectivity/src/scp-cf/destination/service-binding-to-destination.ts, packages/connectivity/src/scp-cf/environment-accessor/service-bindings.ts, packages/connectivity/src/scp-cf/token-accessor.ts, packages/generator-common/src/file-writer/create-file.spec.ts, packages/odata-common/src/request/odata-request.ts, yarn.lock
This allows to set `forwardAuthToken` on all types of destinations. Previously this was only possible for registered destinations.
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1121.
=> feat: Support `forwardAuthToken` for all types of destinations

packages/openapi-generator/src/generator.spec.ts, packages/openapi-generator/src/generator.ts
I noticed, that the prettier config file is read once per schema file. This is not necessary as it is read once before and can be reused.
=> chore: read prettier config once

.changeset/brave-tables-fetch.md, packages/odata-common/src/de-serializers/default-de-serializers.ts, packages/odata-v2/src/de-serializers/payload-value-converter.spec.ts, packages/odata-v4/src/de-serializers/default-de-serializers.ts
For odata-v2, Edm.decimal should always serialize as a string. This PR reverts the change for odata-v2 done in https://github.com/SAP/cloud-sdk-js/pull/4020.
Closes SAP/cloud-sdk-backlog#1087.
=> fix: revert v2 serializer behavior for Edm.decimal

.changeset/happy-mirrors-explain.md, .changeset/three-fireants-happen.md, packages/connectivity/package.json, packages/connectivity/src/http-agent/http-agent.spec.ts, packages/connectivity/src/http-agent/http-agent.ts, packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/connectivity-service-types.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-proxy-configuration.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service.ts, packages/connectivity/src/scp-cf/destination/http-proxy-util.spec.ts, packages/connectivity/src/scp-cf/destination/http-proxy-util.ts, packages/http-client/src/http-client-types.ts, packages/http-client/src/http-client.spec.ts, packages/http-client/src/http-client.ts
Remove http(s) proxy agents and replace them with the native axios config. Apparently, the agents stopped working on cloud connector as they try to setup multiple connections when there is a `data` property in the request 🙀
The decision to use the http(s) proxy agents was made, because we wanted to be able to combine proxies + certificate options. 
=> This was not possible before and might only work with node 20.
Closes #4152
=> fix: Fix proxy configuration for SAP Cloud Connector

package.json, yarn.lock
=> Revert "chore(deps-dev): bump typedoc from 0.25.0 to 0.25.2"

.github/workflows/blackduck.yml, packages/connectivity/src/scp-cf/authorization-header.ts
With this PR, Blackduck will no longer fail if vulnerabilities are found in our test packages.
=> fix: exclude test-directories from blackduck scan

.changeset/great-ads-live.md, .changeset/witty-suns-vanish.md, packages/connectivity/src/scp-cf/authorization-header.spec.ts, packages/connectivity/src/scp-cf/authorization-header.ts
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1160
Fix NoAuthentication for proxytype "OnPremise". This behavior existed only due to a historic bug, which was worked around like this.
We contacted the colleagues from BTP connectivity and learned that this headers is in fact not needed (and incorrect) when using NoAuthentication.
=> fix: allow noauthentication destinations with proxytype “OnPremise”

.changeset/funny-weeks-warn.md, .changeset/gorgeous-dogs-beam.md, packages/connectivity/src/scp-cf/circuit-breaker.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-authentication-type.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-failure-cases.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-jwks.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-provider-subscriber-lookup.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor-proxy-configuration.spec.ts, packages/connectivity/src/scp-cf/destination/destination-accessor.ts, packages/connectivity/src/scp-cf/destination/destination-cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/destination/destination-selection-strategies.ts, packages/connectivity/src/scp-cf/destination/destination-service-cache.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service.ts, packages/http-client/src/http-client.spec.ts, packages/mail-client/package.json, packages/mail-client/src/mail-client.spec.ts, packages/odata-v2/src/request-builder/get-all-request-builder.spec.ts, packages/openapi/src/openapi-request-builder.spec.ts, test-packages/integration-tests/test/v2/request-builder.spec.ts, test-resources/test/test-util/destination-service-mocks.ts, test-resources/test/test-util/example-destination-service-responses.ts, test-resources/test/test-util/token-accessor-mocks.ts, test-resources/test/tsconfig.json
Closes SAP/cloud-sdk-backlog#1158.
Fetch (and cache, if needed) only one destination instead of all available destinations. With this we can currently make just one request for the metadata, instead of 2.
=> chore: Fetch one destination instead of all

.changeset/tasty-shoes-joke.md, packages/connectivity/src/http-agent/http-agent.ts, packages/http-client/src/http-client.ts
Currently I am using the whole file for both the key and certificate. That way we don’t have to parse the content of the certificate and it seems that the https agent can parse it on its own.
=> feat: Support PEM certificates for ClientCertificateAuthentication

packages/connectivity/src/http-agent/http-agent.spec.ts
I forgot to add a unit test for PEM support => https://github.com/SAP/cloud-sdk-js/pull/4473.
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1178.
=> chore: add PEM test

.changeset/silver-melons-tell.md, .github/actions/check-pr/index.js, build-packages/check-pr/validators.spec.ts, build-packages/check-pr/validators.ts
PR checks recently started failing. I found that this is due to the `"` instead of `'` in the changesets. This PR allows both.
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1185
=> chore: fix PR check

.changeset/giant-dolls-arrive.md, packages/openapi-generator/src/file-serializer/schema.spec.ts, packages/openapi-generator/src/file-serializer/schema.ts, test-packages/test-services-openapi/swagger-yaml-service/schema/test-entity.d.ts, test-packages/test-services-openapi/swagger-yaml-service/schema/test-entity.ts, test-packages/test-services-openapi/test-service/schema/complex-test-entity.d.ts, test-packages/test-services-openapi/test-service/schema/complex-test-entity.ts, test-packages/test-services-openapi/test-service/schema/cyclic-child.d.ts, test-packages/test-services-openapi/test-service/schema/cyclic-child.ts, test-packages/test-services-openapi/test-service/schema/cyclic-parent.d.ts, test-packages/test-services-openapi/test-service/schema/cyclic-parent.ts, test-packages/test-services-openapi/test-service/schema/schema-123456.d.ts, test-packages/test-services-openapi/test-service/schema/schema-123456.ts, test-packages/test-services-openapi/test-service/schema/simple-test-entity.d.ts, test-packages/test-services-openapi/test-service/schema/simple-test-entity.ts, test-packages/test-services-openapi/test-service/schema/test-entity.d.ts, test-packages/test-services-openapi/test-service/schema/test-entity.ts, test-packages/type-tests/test/openapi/schema.test-d.ts
This allows additional properties in objects, without making other properties have type `any`.
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1184
=> fix: fix generated types for object schemas

.changeset/light-cats-tickle.md, packages/http-client/src/http-client.spec.ts, packages/http-client/src/http-client.ts, packages/odata-common/src/request/odata-request-config.ts, packages/odata-common/src/request/odata-request.spec.ts, packages/odata-v2/src/request-builder/get-all-request-builder.spec.ts, packages/openapi/src/openapi-request-builder.spec.ts, packages/openapi/src/openapi-request-builder.ts
Currently the OpenAPI requestbuilder erroneously does not encode query parameters by default. 
This PR fixes that.
Closes SAP/cloud-sdk-backlog#1182.
=> fix: fix default encoding in openapi

README.md
https://sap.github.io/cloud-sdk/api/3.0.0/ -> 404
https://sap.github.io/cloud-sdk/api/latest/ -> ✅
=> chore: fix 404 in link to documentation

.changeset/five-socks-confess.md, packages/odata-common/src/request-builder/request-builder-base.ts, packages/odata-common/src/request/odata-request-config.ts, packages/openapi/src/openapi-request-builder.spec.ts, packages/openapi/src/openapi-request-builder.ts
Relates to https://github.com/SAP/cloud-sdk-js/issues/4488
The `addCustomRequestConfiguration` method on a request builder accepts an object in the form of Record<string, string>. However axios accepts other types than string as well.
=> fix: Fix custom request config type

.changeset/seven-shoes-do.md, packages/connectivity/src/scp-cf/destination/destination-service.spec.ts, packages/connectivity/src/scp-cf/destination/destination-service.ts
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1190
Fix check based on which subaccount destination array is returned. This leads to the warning log appearing if there is only one destination at instance level and not at sub-account level.
=> fix: Fetch destination array by type in `fetchDestinationWithoutTokenRetrieval` 

packages/connectivity/src/scp-cf/authorization-header.ts, packages/connectivity/src/scp-cf/destination/destination.ts, packages/util/src/object.ts
I noticed this unnecessary function while investigating a user issue and I found it harder to read than necessary.
=> chore: Remove `toAuthorizationHeader` and `assoc` function

.github/workflows/build.yml, .github/workflows/bump.yml
I found that we were using the events api (`github.event.inputs`), which always gives you a string and I replaced it with the context api (`intputs`) that preserves the type.
This does not explain why it was previously necessary to compare to a boolean on strings, but I guess it has something to do with how it is compared and that `github.event.inputs.skip-checks` was falsy.
Also, I remoed the skip-check and always skip checks when running the canary build
=> chore: (really) fix canary build

.github/workflows/blackduck.yml, .github/workflows/build.yml, .github/workflows/fosstars-report.yml, .github/workflows/memory-tests.yml
With this PR, we update the slack action to 2.3.0, 2.3.0 created a breaking change, where we now have to fill the message and author with actual values.
=> chore: Update slack-notify

packages/connectivity/src/scp-cf/environment-accessor/xsuaa.spec.ts, packages/connectivity/src/scp-cf/environment-accessor/xsuaa.ts, packages/connectivity/src/scp-cf/xsuaa-service.ts
Fix the xsuaa service cache key to be applicable to all services. `serviceInstanceId` does not exist in the destination service credentials.
Also, our E2E tests detected, that the way we consume the token fetching functions from xssec is incorrect. `tenant` is the `subdomain` not the tenant ID as we assumed.
=> chore: fix xsuaa service cache and subdomain

packages/connectivity/src/scp-cf/connectivity-service.ts
I accidentally found this usage of the credentials. This has been deprecated for a while, must have slipped through the review.
=> chore: Remove unnecessary passing of deprecated credentials option

.changeset/quick-points-return.md, packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/destination/destination-cache.ts, packages/connectivity/src/scp-cf/jwt.ts, packages/connectivity/src/scp-cf/tenant.ts, packages/connectivity/src/scp-cf/xsuaa-service.ts
With this PR, we are renaming tenantId to getTenantId and are exposing it to users, so that they have additional convenience, especially when setting tenant headers, which is a requirement for multi-tenant applications running against on-premise transparent proxy destinations.
=> chore: expose getTenantId function

.changeset/long-rivers-wait.md, packages/connectivity/src/scp-cf/connectivity-service.spec.ts, packages/connectivity/src/scp-cf/connectivity-service.ts
With this PR, we add multi-tenancy support for on-premise mail destinations, by fetching tenant-aware connectivity service tokens.
=> feat: Add mutli-tenancy support for on-premise mail destinations

.changeset/chatty-parrots-dream.md, packages/connectivity/src/scp-cf/connectivity-service.ts, packages/connectivity/src/scp-cf/destination/get-subscriber-token.ts
Remove imports from '@types/jsonwebtoken'
=> fix: Fix import of jsonwebtoken types

package.json
Our unit tests are flaky. The reason is most likely that we mock the file system and the tests run concurrently.
=> chore: Turn off concurrency for tests

.changeset/afraid-parrots-run.md, packages/connectivity/src/scp-cf/destination/destination-accessor.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts, packages/connectivity/src/scp-cf/identity-service.ts, packages/connectivity/src/scp-cf/token-accessor.ts
The token exchange was looking at the token's audiences before and basically did a token verification for XSUAA in the case of IAS tokens. This is incorrect, the token should be merely exchanged.
=> fix: fix token exchange

.github/workflows/tests-windows.yml
=> chore: Remove dup concurrency flag in windows workflow

.changeset/calm-candles-lie.md, .changeset/selfish-cougars-shout.md, packages/connectivity/src/scp-cf/destination/__snapshots__/destination-from-registration.spec.ts.snap, packages/connectivity/src/scp-cf/destination/destination-from-registration.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-registration.ts
Currently, for IAS tokens we do not read the correct key for the tenant, when registering destinations.
=> fix: Fix reading correct tenant for destination caching

packages/openapi-generator/src/generator.ts, packages/openapi-generator/src/options/generator-options.spec.ts, packages/openapi-generator/src/options/options.ts, packages/openapi-generator/src/parser/api.spec.ts, packages/openapi-generator/src/parser/document.spec.ts, packages/openapi-generator/src/parser/media-type.spec.ts, packages/openapi-generator/src/parser/operation.spec.ts, packages/openapi-generator/src/parser/options.ts, packages/openapi-generator/src/parser/refs.spec.ts, packages/openapi-generator/src/parser/refs.ts, packages/openapi-generator/src/parser/request-body.spec.ts, packages/openapi-generator/src/parser/responses.spec.ts, packages/openapi-generator/src/parser/schema-naming.spec.ts, packages/openapi-generator/src/parser/schema.spec.ts, packages/openapi-generator/src/parser/unique-naming.spec.ts, packages/openapi-generator/test/test-util.ts
This PR adds new option `schemaPrefix` for openapi generator. Its primarily for internal usage by us for the ai sdk
=> chore: Add schemaprefix option

.changeset/plenty-vans-mix.md, packages/openapi-generator/src/parser/media-type.spec.ts, packages/openapi-generator/src/parser/media-type.ts
Closes SAP/cloud-sdk-js#4969.
As we currently do not support handling charset, the changes in this PR simply ignores the provided charset in the spec and only considers the base media-type. So `application/json;charset=utf-8` would be read as `application/json` and underlying schema is parsed accordingly. Currently it is up to the user to provide any `Accept` and `Content-Type` headers as required by the individual API.
=> fix: Ignore charset parameter in media-types

.changeset/chilled-colts-heal.md, packages/generator-common/src/compiler.ts
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1256
As explained in the ticket.
=> fix: Add nodenext option

.changeset/neat-parents-search.md, packages/connectivity/src/index.ts, packages/connectivity/src/scp-cf/destination/service-binding-to-destination.spec.ts, packages/connectivity/src/scp-cf/destination/service-binding-to-destination.ts
With this PR, we add a default transform function our users can use to build client credentials-based destinations.
Closes SAP/cloud-sdk-backlog#1258.
=> feat: Add default transform function for service bindings

.github/workflows/build.yml, major-release-changeset.md
The release with tag next is version [3.24.1-20241205152930.0](https://www.npmjs.com/package/@sap-cloud-sdk/http-client/v/3.24.1-20241205152930.0) which is a bit misleading. 
https://www.npmjs.com/package/@sap-cloud-sdk/http-client?activeTab=versions
This PR adjusts build workflow so we release a version 4.0.0-20241207 with the tag next. This PR should be reverted once v4 is released. In case we forget, there is a check in the step so we dont mistakenly release v5 canary.
~~- [ ] If my change will be merged into the `main` branch (for v4), I've updated (V4-Upgrade-Guide.md)[./V4-Upgrade-Guide.md] in case my change has any implications for users updating to SDK v4~~
=> chore: Release major `next` 

.github/workflows/auto-dependabot-fix.yml
Automatically fixes dependency issues of dependabot PRs by re-compiling and committing any potential diff.
Part of SAP/cloud-sdk-backlog#1260.
=> chore: Create dependabot PR automation

.github/workflows/auto-dependabot-fix.yml
~Closes SAP/cloud-sdk-backlog#ISSUENUMBER.~
I have to use `pull_request_target` as I saw in https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/, dependabot created PRs are treated as **from a fork** if using `pull_request`
=> chore: Fix auto dependabot workflow using `pull_request_target`

.github/workflows/auto-dependabot-fix.yml
Use `pull_request_target` instead of `pull_request` for dependabot PR to get write access.
=> chore: Use `pull_request_target` in auto-dependabot-fix.yml

.github/workflows/auto-dependabot-fix.yml
Cherry picked commit for PR - https://github.com/SAP/cloud-sdk-js/pull/5286
- ~[ ] If my change will be merged into the `main` branch (for v4), I've updated (V4-Upgrade-Guide.md)[./V4-Upgrade-Guide.md] in case my change has any implications for users updating to SDK v4~
=> chore: use pull_request_target

.changeset/nice-comics-punch.md, packages/connectivity/src/scp-cf/jwt/jwt.ts
=> fix: Reintroduce option to pass iss in getClientCredentials function

.github/workflows/next-build-nightly.yml
=> chore: Add workflow dispatch for v4 canary release job

.github/workflows/next-build-nightly.yml
Successful run: https://github.com/SAP/cloud-sdk-js/actions/runs/13412094350
=> chore: fix nightly canary release workflow

.changeset/seven-crabs-act.md, V4-Upgrade-Guide.md, packages/connectivity/src/scp-cf/identity-service.spec.ts, packages/connectivity/src/scp-cf/identity-service.ts
Relates to SAP/ai-sdk-js-backlog#192.
=> feat!: Disable `iasToXsuaaTokenExchange` by default

.changeset/salty-teams-follow.md, packages/connectivity/src/scp-cf/connectivity-service.spec.ts, packages/connectivity/src/scp-cf/connectivity-service.ts, packages/connectivity/src/scp-cf/destination/destination-from-service.ts
We do not cache destination with `proxyConfiguration` any more. The proxy configuration will be added every time after a destination is fetched from or not from cache. 
Client credential token is cached anyway already so no performance issue when keep calling `serviceToken()` to set proxy authorization token.
Closes SAP/cloud-sdk-backlog#1255.
Fix https://github.com/SAP/cloud-sdk-js/issues/5131
=> fix: `Proxy-Authorization` token expired issue for cached destination

build-packages/check-pr/validators.spec.ts, package.json, packages/connectivity/src/http-agent/http-agent.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-registration.spec.ts, packages/generator-common/src/compiler.spec.ts, packages/generator/src/generator.spec.ts, test-packages/e2e-tests/test/odata-generator-cli.spec.ts, test-packages/integration-tests/test/mtls.spec.ts
Our pipeline got flaky because some of the mock-fs logic is bleeding into other tests, to isolate tests as much as possible, all mocking is now beforeEach / afterEach, so that we prevent bleeding.
Also increased the client generation timeout, because the github runners seem to run into the timeout frequently.
Closes https://github.com/SAP/ai-sdk-js-backlog/issues/247
=> chore: Fix mock-fs flakiness

.changeset/tame-spoons-kiss.md, .github/dependabot.yml, packages/eslint-config/package.json
`@stylistic/eslint-plugin` v4 (not Cloud SDK v4 😄 ) supports ESM only. [Release Note v4.0.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v4.0.0) However, we are still on CJS. 
Also, starting from v4, they do not support legacy config but only flat config. But we currently support both config files. So if user uses legacy config and we upgrade to `@stylistic/eslint-plugin` v4, it will break.
Further discussion required for long-term support, but as for now, I will downgrade to v3.
---
I will create a PR for SDK v3 as it also breaks their..
=> fix: Downgrade `@stylistic/eslint-plugin` to `v3.1.0`

.changeset/tame-spoons-kiss.md, .github/dependabot.yml, packages/eslint-config/package.json
=> fix: Downgrade `@stylistic/eslint-plugin` to `v3.1.0` (#5608)

.changeset/twenty-ideas-sleep.md, packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts, packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts, yarn.lock
Closes SAP/ai-sdk-js-backlog#256.
Fix user issue #5631.
In #5563, we cache only partial destination without `proxyConfiguration` to allow it being added on the fly after cache retrieval. This works well when calling `getDestinationFromDestinationService()` directly. 
However, since `searchServiceBindingForDestination()` and `getDestinationFromDestinationService()` are sharing one destination cache, and vcap search comes first, it intercepts the cache retrieval and causing `proxyConfiguration` being not added in `getDestinationFromDestinationService()`. 
My first thought was to separate the caches for both functions. But it is not possible because we export `setDestinationCache()` from `destination-cache.ts` to allow user using their own cache object. And we cannot clone such object. …
=> fix: Remove destination cache when getting destinations from service binding

packages/openapi/src/openapi-request-builder.spec.ts
Tests were flaky. My guess is that the `delayInResponse` is too small (was 10ms). The pseudo timer cannot really be used for such high precision task (difference of 5ms).
=> chore: Fix openapi request builder test

.github/workflows/check-pr.yml
As tj-actions owners did not prove to have safeguarded their organization, it is better to not trust the organization anymore.
=> chore: Change from tj-actions/changed-files to step-security/changed-files

.github/actions/merge-and-write-changelogs/index.js, build-packages/merge-and-write-changelogs/index.ts
`bump` script failed recently while trying to release the AI SDK because for the below changelog added:
```
- 627a152: [Compatibility Note] Removed deprecated models: 
- `text-embedding-ada-002`, use `text-embedding-3-small` or `text-embedding-3-large` instead. 
- `meta--llama3-70b-instruct`, use `meta--llama3.1-70b-instruct` instead. 
- `gpt-35-turbo`, use `gpt-4o-mini` instead. 
- `gpt-35-turbo-16k`, use `gpt-4o-mini` instead. - `gpt-4-32k`, use `gpt-4o` instead.
```
The action tries to greedily match the `:` and fails to determine the type i,e Compatibility Note.
This PR fixes the issue and matches the type and commit correctly.
I ran the script locally to see if the change is successful and the changelog is generated successfully.
=> chore: Adapt regex in merge and write changelog action

.github/dependabot.yml
See https://github.com/SAP/cloud-sdk-js/pull/5815.
`yargs` v18 requires ESM.
=> chore: Ignore major update for `yargs` due to ESM
